### ISSUE TITLE
Clarify installation steps

### ISSUE THREAD

**Issue by mcandre** [google/pprof#112]
As a Go newbie, I've been configuring both my `$GOROOT` and `$GOPATH` as `/go`. However, pprof refuses to build with this setup.

```console
$ go get github.com/google/pprof
warning: GOPATH set to GOROOT (/go) has no effect
package github.com/google/pprof: cannot download, $GOPATH must not be set to $GOROOT. For more details see: go help gopath
```

I tried `mkdir -p /go-special && export GOPATH=/go-special`, but the pprof build/installation process doesn't like that either.

Could the README please be more explicit about the right way to do this?

**Comment by rauls5382** [comment]
This isn't specific to pprof, but a Go question. See here:
http://stackoverflow.com/questions/22877775/gopath-must-not-be-set-to-goroot-why-not

I will update the README with some suggestions.
