### ISSUE TITLE
"Total samples" as milliseconds is confusing

### ISSUE THREAD

**Issue by bcmills** [google/pprof#128]
`pprof` output currently includes a line of the form:

```
Duration: 1.60s, Total samples = 14.50ms (  0.9%)
```

The "Total samples" part is confusing.  Milliseconds are continuous, but samples are discrete — they're individual points, so how can you sum them up into a quantity of milliseconds?

I seem to recall that an earlier (pre-GitHub) version of pprof reported the number of samples as an actual number of samples.  Can we please go back to that?  Otherwise, please update the formatting of the `Duration` line to give a clearer indication of what a quantity of samples reported in milliseconds actually means.

**Comment by rauls5382** [comment]
Each callstack in a profile is associated to a set of values. What is reported here is the sum of these values for all the callstacks in the profile, and is useful to understand the weight of individual frames over the full profile.

profile.proto is an unsampled format, so we in general do not have access to the number of samples collected.

**Comment by bcmills** [comment]
My point is that the "sum" is the sum of a discrete number (a quantity of samples), not a continuous range (a time interval).  Reporting the sums makes perfect sense, but reporting discrete numbers using continuous units is just plain confusing.

**Comment by bcmills** [comment]
Or, to put it a different way: even if we don't have access to the number of samples, we should report the quantities in some unit that doesn't (erroneously) suggest continuity.

**Comment by rauls5382** [comment]
We're reporting the sum using the unit described in the profile.
Would you have a concrete suggestion for this example? Maybe just a rewording would help, like:

Duration: 1.60s, Samples account for 14.50ms (0.9%)

**Comment by bcmills** [comment]
Rewording would help a little, but it's still confusing: if you say "Samples account for 14.50ms", how do you know the duration of each of those samples?

What does it mean to say the samples "account for 14.50ms" on a 2.5GHz CPU with 4-wide instruction dispatch (as is typical for modern AMD64 implementations)?  Does that mean that the sampled instructions were the most recently dispatched instruction for each of 36,250,000 clock cycles?  Does it mean that the instructions saturated the ALU for that many clock cycles?  Something else entirely?

When you're dealing with a sample-based system, it's meaningful to talk about total times and fractions of the total sample.  Fractions of the total time are nonsensical: it's like choosing 10 points along a 1-meter line and claiming that those points account for three centimeters of the line.
