### ISSUE TITLE
Please clarify relationship to `go tool pprof`

### ISSUE THREAD

**Issue by AlekSi** [google/pprof#132]
https://github.com/golang/go/tree/master/src/cmd/pprof
My understanding that they are historically related, but no longer share code. A note in README would be useful.

**Comment by AlekSi** [comment]
> but no longer share code

Well, they do share code – Go pprof tool imports this package. :)

**Comment by rsc** [comment]
I'll update the README in our tree. Closing this issue since it's not about the google/pprof repo.

**Comment by AlekSi** [comment]
In fact, [`pprof.go`](https://github.com/golang/go/blob/master/src/cmd/pprof/pprof.go#L5) in Go repository already has a comment about this. I wasn't attentive enough. Still, cross-reference may be useful.

**Comment by rsc** [comment]
https://go-review.googlesource.com/40231

**Comment by AlekSi** [comment]
@rsc 404 for me, is it expected?

**Comment by rsc** [comment]
I can't reproduce the 404. Works fine for me. Try https://go-review.googlesource.com/c/40231/ or golang.org/cl/40231 instead.

**Comment by aalexand** [comment]
I get 404 as well.

**Comment by rsc** [comment]
Apparently Gerrit is having its own issues today. Sorry about the 404s.

**Comment by aalexand** [comment]
Opens for me now.
