### ISSUE TITLE
golang pprof should support --symbols mode to match perl pprof

### ISSUE THREAD

**Issue by alk** [google/pprof#141]
Right now some amount of code in gperftools is relying on pprof --symbols (invoked via symbolize.cc). And apparently golang version doesn't support this flag. Can this support be added?

**Comment by rauls5382** [comment]
I'm weary of adding such a functionality to pprof, as it is outside of pprof's core function (profile visualization). If this is useful, I suggest to make a separate tool, a variant of addr2line.

**Comment by rsc** [comment]
I agree: this is not pprof's job and should not be carried forward.
