### ISSUE TITLE
`failed to access temp dir /pprof: mkdir /pprof: Access is denied.` on Windows when PPROF_TMPDIR is not set

### ISSUE THREAD

**Issue by realityexists** [google/pprof#148]
When I run `go tool pprof myfile.prof` on Windows I get an error: `failed to access temp dir /pprof: mkdir /pprof: Access is denied.` Setting PPROF_TMPDIR to a valid directory works around this.

I suspect what happens is that PPROF_TMPDIR ignores the fact that %HOME% is empty on Windows and still uses "%HOME%/pprof" as the default value of PPROF_TMPDIR. It should probably
1) Use %TEMP% on Windows.
2) Check that $HOME is not empty before using it (everywhere).

(Go version 1.8.3. pprof version unknown, since it's not displayed anywhere that I can find.)

**Comment by nolanmar511** [comment]
Based on our documentation, we should be using "%USERPROFILE%/pprof" on windows when no value is set for PPROF_TMPDIR. 
Just to double check, do you know if there was a value for %USERPROFILE% when you had this error?

**Comment by realityexists** [comment]
Yes, I have %USERPROFILE% set. It's easily reproducible by running `go tool pprof blah` - it doesn't seem to matter whether the file "blah" exists or not.

**Comment by nolanmar511** [comment]
I've tried running the latest version of pprof, with go version 1.8.3, on a Windows  machine when %PPROF_TEMPDIR% is not set. However, I wasn't able to replicate this error.

Do you how recent your version of pprof is, or if this problem persists for you with the latest version? Could it be related to your version of windows (I ran this on a computer with Windows 10 Home)?

**Comment by aalexand** [comment]
Note that the user runs `go tool pprof myfile.prof` here, which uses pprof that is part of Go distribution.

**Comment by aalexand** [comment]
Maybe this is https://github.com/golang/go/issues/18864 which was fixed in https://github.com/google/pprof/pull/95?

**Comment by realityexists** [comment]
Yes, it looks like the same issue to me. I would still suggest checking that whatever environment variable you picked is not empty before appending a sub-path to it. Doing that would have given a clearer error here. Also, in one case `filepath.Join(os.Getenv(homeEnv()), ...` is used and in another case `os.Getenv(homeEnv()) + "/pprof"` - not sure if that's safe on Windows.

**Comment by aalexand** [comment]
Using filepath.Join() consistently and not using empty string as an absolute path prefix are all reasonable things, yes.
