### ISSUE TITLE
tagfocus issues with size

### ISSUE THREAD

**Issue by ahh** [google/pprof#153]
(again, silly zipped profile for github naming)

```
pprof -raw heapz
Samples:
objects/count space/bytes[dflt]
       7438   60936269: 1 2 3 4 5 6
                bytes:[8192] request:[8191]
        238   62466710: 7 8 9 10 5 6
                bytes:[262144] request:[262143]
       3341   54739221: 7 8 9 10 5 6
                bytes:[16384] request:[16383]
       2064   67634517: 1 2 3 4 5 6
                bytes:[32768] request:[32767]
      29710   60847108: 1 2 3 4 5 6
                bytes:[2048] request:[2047]
        396   51920894: 1 2 3 4 5 6
                bytes:[131072] request:[131071]
      63503   65027585: 7 8 9 10 5 6
                bytes:[1024] request:[1023]
       1105   72423082: 7 8 9 10 5 6
                bytes:[65536] request:[65535]
        108   56884975: 11 12 13 3 4 5 6
                bytes:[524288] request:[524287]
      15887   65075220: 7 8 9 10 5 6
                bytes:[4096] request:[4095]
```

Now let's try to filter to some of these. Each of the below queries should match exactly one entry and do (this is good)

```
pprof -traces -tagfocus=4096bytes heapz
pprof -traces -tagfocus=4095request heapz
pprof -traces -tagfocus=4kb heapz
pprof -traces -tagfocus=512kb heapz
pprof -traces -tagfocus=524288bytes: heapz
```

But this matches everything:
```
pprof -traces -tagfocus=512kb: heapz
```

Note that `524288 bytes = 512kb`.  But for some reason when we have a non-empty *range* that breaks. That's a flat bug.  `:1kb` seems to work, otoh, as does `1kb:4kb`.

A slightly different problem is that there's no easy way to specify request ranges without having to write out full numbers.  I'd be very happy if I could specify, say:

```-tagfocus=/request/256kb:512kb```

to mean "I want to see a tag, whose name matches "request", whose value is between 256kb and 512kb.

[heapz.zip](https://github.com/google/pprof/files/1131710/heapz.zip)

**Comment by aalexand** [comment]
@nolanmar511  Is this issue still relevant?

**Comment by nolanmar511** [comment]
It's still not resolved, but I think it should be fixed when/by adding units to tags.

**Comment by aalexand** [comment]
@nolanmar511 Should we mark this issue as fixed now?

**Comment by nolanmar511** [comment]
I think so.
