### ISSUE TITLE
Make sure Travis (and Appveyor) environment has graphviz installed

### ISSUE THREAD

**Issue by aalexand** [google/pprof#170]
Saw this message in the travis test logs:
```
--- PASS: TestWebInterface (0.00s)
	webui_test.go:76: skpping / since dot (graphviz) does not seem to be installed
```
We should make sure we have graphviz installed so that tests don't skip this. Bonus for fixing the typo "skpping" -> "skipping" :)

**Comment by nolanmar511** [comment]
This has been added
