### ISSUE TITLE
Install golang from soure will ramdomly fail at runtime/pprof	

### ISSUE THREAD

**Issue by easonyzwang** [google/pprof#172]
I am using go1.7 to bootstrap go1.8, install from source, since my system `CentOS/RHEL 5.x not supported`

All my go env setting:
```
export GOBIN=""
export GOEXE=""
export GOHOSTARCH="amd64"
export GOHOSTOS="linux"
export GOPATH="/root/go"
export GORACE=""
export GOTOOLDIR="/opt/elasticbeanstalk/lib/go/pkg/tool/linux_amd64"
export GCCGO="gccgo"
export CC="gcc"
export GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build601233908=/tmp/go-build -gno-record-gcc-switches"
export CXX="g++"
export CGO_ENABLED="1"
export PKG_CONFIG="pkg-config"
export CGO_CFLAGS="-g -O2"
export CGO_CPPFLAGS=""
export CGO_CXXFLAGS="-g -O2"
export CGO_FFLAGS="-g -O2"
export CGO_LDFLAGS="-g -O2"
ort GOTOOLDIR="/opt/elasticbeanstalk/lib/go/pkg/tool/linux_amd64"
export GCCGO="gccgo"
export CC="gcc"
export GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build601233908=/tmp/go-build -gno-record-gcc-switches"
export CXX="g++"
export CGO_ENABLED="1"
export PKG_CONFIG="pkg-config"
export CGO_CFLAGS="-g -O2"
export CGO_CPPFLAGS=""
export CGO_CXXFLAGS="-g -O2"
export CGO_FFLAGS="-g -O2"
export CGO_LDFLAGS="-g -O2"
```
I think those env-variables are correct since it could be successfully installed. But in my install-golang-script, it will roughly 30% fail, after I run .`/all.bash`. 

All of the fail is in `testing packages stage` due to
```
 *** Test killed with quit: ran too long (4m0s).
FAIL	runtime/pprof	240.050s
```

I tried to set timeout longer, like this:
`export GO_TEST_TIMEOUT_SCALE=10, `
but the result is it will stuck at this stage, more than 10 minutes.

I also tried to set high resolution timer, but still didn't work.
`export CONFIG_HIGH_RES_TIMERS=y`

Anyone know how to fix it ?

**Comment by aalexand** [comment]
runtime/pprof tests are part of Go source, file this under https://github.com/golang/go
