### ISSUE TITLE
tagfocus needs better support for picking which tag to focus on 

### ISSUE THREAD

**Issue by ahh** [google/pprof#178]
Mentioned offhand in #153:

A slightly different problem is that there's no easy way to specify request ranges without having to write out full numbers. I'd be very happy if I could specify, say:

-tagfocus=/request/256kb:512kb

to mean "I want to see a tag, whose name matches "request", whose value is between 256kb and 512kb.

If we can't manage the unit conversion and I have to specify /request/262144:524288, I can work with that for now (though it'd be very nice....)

This is becoming more important as we add more tags to generated profiles, some of which aren't really comparable; they're not tweaked values, they're things with totally different meanings.  (think "requested alignment"; I do not want tagfocus=:512 to pick up every unaligned alloc even if it was a 2 MiB request!

**Comment by aalexand** [comment]
One simple way to address this is to make show filter for tags handled before the tag focus handling (here)[https://github.com/google/pprof/blob/805912e7989642128fbdcec1fc80e04396e6f709/internal/driver/driver_focus.go#L49]

Then it would be possible to do something like `-tagshow=request -tagfocus=256kb:512kb` and it would do what you want I think, except that it wouldn't show you other tags.

**Comment by ahh** [comment]
That would be an OK stopgap, but I generally want to see all the tags, I just want to filter based on particulars.

**Comment by aalexand** [comment]
Maybe we should do the simple thing first then.

For the syntax you proposed, I think I'd prefer the desired tag name to be specified exactly, not a substring or regexp match. That would allow recognizing whether the same tag is requested and handle things like `-tagfocus=mytag=foo -tagfocus=mytag=bar -tagfocus=myothertag=baz` naturally as (mytag == "foo" || mytag == "bar") || myothertag == "baz". From the tag names that I saw so far, I can't see much advantage of being able to regexp match tag names.

**Comment by nolanmar511** [comment]
This is not a solution, but if you really want to try out this functionality right now, you could do something like `-tagfocus=262144request:524288request`, which would allow other tags to be shown. 

This is definitely hack-y and takes advantage of the problems an odd quirk in which tag names are used as units.

**Comment by ahh** [comment]
Regexp was just a half-assed suggestion; exact match I'm totally fine with.

Margaret's solution is in fact a workaround :), but also problematic (I'd
much prefer some way to make "request=512kb" work, it's much more usable.)

**Comment by aalexand** [comment]
@nolanmar511 This is fixed with #183?

**Comment by nolanmar511** [comment]
Yes -- we did fix this with #183
