### ISSUE TITLE
MallocExtension::instance()->GetHeapSample(&output) output no heap profile info

### ISSUE THREAD

**Issue by tanglianggithub** [google/pprof#187]
no heap profile info. only MAPPED_LIBRARIES info.
as follows

![image](https://user-images.githubusercontent.com/3445470/29111878-a0ea9c58-7d1e-11e7-8d80-a40a869b6205.png)

**Comment by rauls5382** [comment]
The profile appears to be empty. This is not an issue with pprof but with the source of the profile.
Are you using gperftools? If so, look into https://github.com/gperftools/gperftools/issues/283
