### ISSUE TITLE
Can't get java stack frame when trace off-heap memory

### ISSUE THREAD

**Issue by louxiu** [google/pprof#191]
I use gperftools-2.5 to trace java off-heap memory leak, but I can't find which method called `Unsafe_AllocateMemory`.
![leak](https://user-images.githubusercontent.com/925154/29457168-6d7412bc-844b-11e7-9f54-fa98a1b7f0d6.png)

I know that perf can get java stack using [Mixed-Mode](https://www.infoq.com/news/2015/08/JVM-Option-mixed-mode-profiles). I tried that with pprof but without luck. Is it possible to get the java stack frame in pprof? 

also @brendangregg

**Comment by aalexand** [comment]
I would expect that with “-XX:+PreserveFramePointer” stack unwinding is able to get all stack frames and passing the binary path to pprof will make it resolve the native locations. Can you post complete description of what code you are profiling, how you invoke gperftools, how you invoke perf, which platform you are on, what is the pprof version and other details that can help other people reproduce your issue?

**Comment by louxiu** [comment]
Shame on this :-(. I report to the wrong project. The issue is related to [gperftools](https://github.com/gperftools/gperftools). Sorry
