### ISSUE TITLE
"hasAlloc" in legacy_profile.go

### ISSUE THREAD

**Issue by neodooth** [google/pprof#205]
Hi,

My question is about this line:
https://github.com/google/pprof/blob/c1e71a7081001f9be5d1286d1fda9c46714929d9/profile/legacy_profile.go#L568

I can't really understand the meaning of it (and there's only one commit of this chunk). Since I need to use Go 1.7 and it returns profile in legacy format, `hasAlloc` might be false sometimes (sometimes it is true), and this makes alloc objects/space disappear in the output of pprof. It's difficult to analyze the output of pprof programmatically if the fields are changing.

**Comment by rauls5382** [comment]
This was added to detect profiles from an old profile generator that produced only in_use information. It would use the legacy format with the same numbers for for in_use and alloc data.

It should be very unlikely for a Go profile to hit this, as it would indicate that all the memory allocated is currently in use (nothing was ever freed). Are you seeing this in practice?

For your own purposes, it is OK for you to force hasAlloc to true. We could consider making that change on the codebase, as those old profile generators are probably not relevant anymore.

**Comment by neodooth** [comment]
@rauls5382 Thanks for your reply. My situation is that allocated memory and in use memory are the same when the program has just started(no GCs yet); after a while they will be different and inuse/alloc will both show up and then everything's fine. It's a problem for me just because I'm writing a monitor-like tool.

Forcing hasAlloc to be true does work for me. And it may be a good idea to just deprecate this if those generators are really too old; users of them might even don't dare to update their pprof to the current master haha

Thank you!
