### ISSUE TITLE
graph separate functions by filename+name by default

### ISSUE THREAD

**Issue by jendap** [google/pprof#206]
### What version of pprof are you using?
latest - whatever "go get ..." gave me on 8/23/2017

### What did you do?
I have created profile file manually. Not some cpu sampler. But for a good reason. Anyway, there are function names that collide. Prefixing them with the full thing would be very long, ugly and useless (for this case). I have put the prefixes as file_name field Function message in the proto.

Colliding function names are common. Name mangling is ugly. How about colliding functions with the same name but different filename? Has anybody seen it yet? And it is the way the proto is structured already.

### What did you expect to see?
I would expect the graph rendering not to merge the two functions by name but rather by file_name + name. 

Note: "pprof --files ..." does not take file_name from Function but rather from Mapping.

**Comment by aalexand** [comment]
> Note: "pprof --files ..." does not take file_name from Function but rather from Mapping.

I am not sure about that. Running something like `pprof -top -files ~/Downloads/profile.pb.gz` for a Java profile does get me Java source file names in the output.

@rauls5382 What do you think about adding `-functionfiles` granularity which would aggregate profile leaving function and file name?

**Comment by jendap** [comment]
"pprof -files" will work if the profile has multiple Mapping(s) in it. And one has to add the "-files" argument which is impractical in way some organizations use pprof.

I don't think there should be new command line flag.

Why not just change the current "-functions" to merge noes on name+file_name instead of name alone? After all the flag is "-functions" not "-function-names" so it should respect the Function record not just one of its fields, right?

**Comment by rauls5382** [comment]
IIRC, pprof will not merge functions with the same name and different source files.
The source files is meant to be a file path. We do some cleanup that could be problematic.

The Function message has a field called "SystemName" which can be used to differentiate between  functions with the same name.

A sample profile would be useful to understand/validate the problem.

**Comment by jendap** [comment]
system_name will just override name in the graph - so whatever one can put to system_name can be put to name directly (as far as graphs is concerned at least)

The following profile will create two nodes instead of three directly linked.

%%multicell
profile_prototxt = '''
sample_type {
  type: 1
  unit: 2
}
sample {
  location_id: 1
  value: 10
}
sample {
  location_id: 2
  location_id: 1
  value: 10
}
sample {
  location_id: 3
  location_id: 2
  location_id: 1
  value: 10
}
mapping {
  id: 1
  has_functions: true
  has_filenames: true
}
location {
  id: 1
  mapping_id: 1
  line {
    function_id: 1
  }
}
location {
  id: 2
  mapping_id: 1
  line {
    function_id: 2
  }
}
location {
  id: 3
  mapping_id: 1
  line {
    function_id: 3
  }
}
function {
  id: 1
  name: 3
  filename: 5
}
function {
  id: 2
  name: 4
  filename: 6
}
function {
  id: 3
  name: 3
  filename: 7
}
string_table: ""
string_table: "memory"
string_table: "bytes"
string_table: "foo"
string_table: "bar"
string_table: "a"
string_table: "b"
string_table: "c"
'''
# from google.protobuf import text_format
profile = Profile()
text_format.Merge(profile_prototxt, profile)
open('/tmp/profile001.pb', 'wb').write(profile.SerializeToString())
%%endcell
%%shell
pprof --notrim --png --output /tmp/profile001.png /tmp/profile001.pb && eog /tmp/profile001.png && rm /tmp/profile001.*

**Comment by rauls5382** [comment]
SystemName should not be override Name by default. I've sent #210 to address that.

I confirmed that pprof is grouping based only on the printable name. I believe that was done to merge C++ functions instantiations (eg combine all std::vector::push_back into a single node).

I'm not keen on printing multiple rows with the same name, as you would not be able to differentiate between them. Have you considered adding a disambiguator to the names (eg foo/1 foo/2) to prevent merging?

**Comment by jendap** [comment]
Right, C++ templates needs that :( Looking at first c++ profile there are some questionable merges like "operator()" or "get" which are in my case not supposed to be merged. But it is still 1000x better then not merging the templates.

Which means this behaviour make sense to do this for pprof. Thanks!

**Comment by jendap** [comment]
BTW: This merging is actually very good to understand for users. Merging a lot of unrelated nodes via merging "operator()" from std::function accounts for big part of the mess in was seeing in those graphs.
