### ISSUE TITLE
Web UI plans

### ISSUE THREAD

**Issue by ghemawat** [google/pprof#207]
I wanted to open a discussion about the road-map for the web interface.  The things I can think of that need doing:

- Flesh out the interface to cover important output modes. Flame graph PR is already in progress, but perhaps there are others?

- Support for importation options like granularity, sample_index, etc.

- Sort-able columns in the top display

- Add consistency to the source and disassembly listings (they are missing the menu bar and navigation to other views).

- Tweaks (e.g., top display should handle ultra long names better).

- Test on various browsers

- On-line help

- Maybe: make the top display the default so that we don't unnecessarily compute the dot graph for people who don't want it (e.g., people who are looking for a flame graph).

- Maybe: automatically open the web interface even without an -http flag (while still allowing the text interface as well)?

Any other ideas?

### What version of pprof are you using?
01dfac5
### What operating system and processor architecture are you using?
NA
### What did you do?
NA

**Comment by aalexand** [comment]
@rakyll @spiermar @josef-jelinek @rauls5382 @nolanmar511

**Comment by aalexand** [comment]
One thing we discussed with @josef-jelinek is that it would be good to switch to using Typescript to catch various typing bugs earlier. This might complicate the build process though (as there would need to be transpilation step).

I think some support for tags would be good. Ability to specify `tagfocus` and `tagignore` as an example.

**Comment by ghemawat** [comment]
We could use go:generate to run typescript.  IIRC, the idea is that owners of the repo run go generate before committing and users of the repo don't need access to the tools run by go generate.  So it will complicate the lives of just people making changes to pprof.

https://blog.golang.org/generate

**Comment by ghemawat** [comment]
FYI, the following are merged:

* Add consistency to the source and disassembly listings (they are missing the menu bar and navigation to other views).
* Tweaks (e.g., top display should handle ultra long names better).

I have a couple of other UI related changes done but pull requests not yet sent out:
* Sort-able columns in the top display
* Header menu entries are proper links so they can be middle and right-clicked (for opening in another tab, copying link address, etc.)

**Comment by pmallela** [comment]
Hi, is it possible to import/integrate the webui portions of this tool into one's own program? I'd like to serve the interactive web ui from within my program, using its own profile, similar to how "net/http/pprof" works. Is this something that has been discussed before?

**Comment by nolanmar511** [comment]
@pmallela -- I don't believe this is something we'd previously discussed. But at this point in time, we are unlikely to expose anything in the /internal folder for maintainability reasons. The webui is something we'd be particularly hesitant to expose right now, given that it's a newer feature and so we are more likely to want to change it in ways which might break dependencies.
Depending on what you are hoping to show, it may be possible to accomplish it by making calls to the pprof CLI.

**Comment by aalexand** [comment]
Most of the things on the list are done now, so the issue feels obsolete. Closing.
