### ISSUE TITLE
Crash found with Fuzzing, Write()

### ISSUE THREAD

**Issue by nolanmar511** [google/pprof#246]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?
commit: 9181e6bcbfdb5cd75bb563332b682b15b0b371b0 

### What operating system and processor architecture are you using?
Linux

### What did you do?
Modified the fuzzer to be :
```
func Fuzz(data []byte) int {
	p, err := profile.ParseData(data)
	if err == nil {
		if _, err := profile.Merge([]*profile.Profile{p,p}); err != nil {
			panic(fmt.Errorf("could not merge profile with self: %v", err))
		}
	}

	// Decompress if compressed.
	if len(data) >= 2 && data[0] == 0x1f && data[1] == 0x8b {
		gz, err := gzip.NewReader(bytes.NewBuffer(data))
		if err == nil {
			data, err = ioutil.ReadAll(gz)
		}
		if err != nil {
			return 0
		}
	}

	// if legacy format, just write out
	if _, err = profile.ParseUncompressed(data); err != nil {
		buf := bytes.NewBuffer(nil);
		p.Write(buf);
		return 0;
	}

	// if non-legacy format, write and compare to input
	buf := bytes.NewBuffer(nil);
	p.Write(buf);
	reEncoded := buf.Bytes();

	if diff, equal := messagediff.PrettyDiff(reEncoded, data); equal {
		panic(fmt.Errorf("Input doesn't match output: \n%s", diff));
	}

	return 0
}

```
Here is a zipped version of the profile which caused the crash. 
[da39a3ee5e6b4b0d3255bfef95601890afd80709.zip](https://github.com/google/pprof/files/1419754/da39a3ee5e6b4b0d3255bfef95601890afd80709.zip)

### What did you expect to see?
I expected no segmentation fault.

### What did you see instead?
There was a segmentation fault when writing out the parsed profile:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x52db9e]

goroutine 1 [running]:
github.com/google/pprof/profile.serialize(0x0, 0x5905d8, 0xc420096420, 0x40fe88)
	/tmp/go-fuzz-build455251141/gopath/src/github.com/google/pprof/profile/profile.go:308 +0x3e
github.com/google/pprof/profile.(*Profile).Write(0x0, 0x636360, 0xc4200cfc70, 0x0, 0x0)
	/tmp/go-fuzz-build455251141/gopath/src/github.com/google/pprof/profile/profile.go:319 +0x97
github.com/google/pprof/fuzz.Fuzz(0x7f8bb0574000, 0x0, 0x200000, 0xc420051f70)
	/tmp/go-fuzz-build455251141/gopath/src/github.com/google/pprof/fuzz/main.go:38 +0x1a1
go-fuzz-dep.Main(0x590648)
	/tmp/go-fuzz-build455251141/goroot/src/go-fuzz-dep/main.go:49 +0xad
main.main()
	/tmp/go-fuzz-build455251141/gopath/src/github.com/google/pprof/fuzz/go.fuzz.main/main.go:10 +0x2d
exit status 2

**Comment by aalexand** [comment]
@nolanmar511 The archive contains an empty file, is that intended?

**Comment by aalexand** [comment]
Your fuzzer seems to fall through if the initial ParseData returned an error (is that intended?), so you seem to just call p.Write() with nil profile then? That's obviously not an interesting crasher, am I missing something?

**Comment by nolanmar511** [comment]
You're right -- that was a major oversight on my part.
