### ISSUE TITLE
Allow multiple sample_index (indices) while sorting by first one

### ISSUE THREAD

**Issue by trivk** [google/pprof#257]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

If you are using pprof via `go tool pprof`, what's your `go env` output?
If you run pprof from Github, what's the Git revision?

### What operating system and processor architecture are you using?
Linux <redacted> 4.4.0-96-generic #119~14.04.1-Ubuntu SMP Wed Sep 13 08:40:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?

This is a feature request.
pprof --sample_index=1 --sample_index=2 -top 25 <Profile proto file>

I want it to show sample_index=1, and sort by it, but also show sample_index=2.

**Comment by aalexand** [comment]
This would be a significant change in pprof and we don't have plans to address this right now.
