### ISSUE TITLE
Improve the CSS of the web UI

### ISSUE THREAD

**Issue by tdewolff** [google/pprof#260]
I was thinking about improving the CSS for the web UI, as I think its usability and aesthetics could be improved. I'm thinking of a UI much alike https://go-review.googlesource.com/q/status:open, which someone has done in the past (for the Go team I believe).

I could make a start with this and add a PR if desired. Additionally it would be good if the webhtml.go file would read off from separate HTML, CSS and JS files, instead of a large text blob in Go.

Is someone working on this, or do we have plans for refactoring or a new UI?

**Comment by aalexand** [comment]
No one is working on this, so if you want to give it a try - go ahead. The only constraint is try to avoid external dependencies and if you want any let's discuss first. pprof is a part of Golang distribution so we try to avoid bloating the size of the distribution (and any resources fetched from the network are not an option at all due to security concerns and general desire to make sure pprof can work on a local machine without any external network connectivity).

**Comment by tdewolff** [comment]
Great, I have a new CSS theme ready at https://github.com/tdewolff/pprof/commit/d99a51554ff6c2e47b2253a1348499ff9e566963

![pprof](https://user-images.githubusercontent.com/5563166/32799474-0225f0f8-c95f-11e7-8b73-c136c989ba71.png)

There is a couple of other things I want to do:
- Organize the HTML, CSS and JS files and separate them, preferably in separate .html, .css and .js files. Is this possible, because then the files are not embedded in the binary. Otherwise at least separate them as strings inside the .go file.
- Refactor JS
- Hide the refine menu on pages other than Graph
- Add keyboard shortcuts for actions on the graph and navigation
- Improve the view of Peek and Disassemble, because right now it is just text output
- Implement #218 

Do you want one big PR, or in pieces (like the commit above)? How do I handle the import path changes for PR merging?

**Comment by aalexand** [comment]
I haven't played with the branch yet, but the UI in the screenshot looks pretty good!

We should keep built pprof stays a single binary, with no need for any resources to be colocated. Having additional files would at least require changing how we distribute pprof to developers' machines here at Google would probably affect other people so I think it's not worth it.

Thoughts on how to sequence the PRs:
* Make any refactoring (JS or separating HTML, CSS and JS) separate PRs.
* Implementing #218 should be a separate PR I think.
* I would make keyboard shortcuts also a separate PR.
* Other things (hide the refine menu, improve the view of peek and disassemble, open details for a click on binary) can probably me the same PR as I feel those are smaller changes?

**Comment by aalexand** [comment]
@tdewolff Closing the issue, please re-open / file more specific ones if you plan to continue this work.
