### ISSUE TITLE
Easy testdata update for internal/driver tests.

### ISSUE THREAD

**Issue by Maaarcocr** [google/pprof#274]
While working on #271 I had to update one of the testdata files in the internal/driver directory. The folder didn't contain any instruction about how to update them.

Do you think that it would be worth creating a way to easily updating the files? Different snapshot testing libraries offer some flags that you can set so that they update the snapshots for you. Would this be useful if added? 

I have hacked together a first draft for this while trying to update the file I had to change in order to make tests pass for #271. This codes lives on a branch on my machine, let me know if you are interested in discussing this further 😄

**Comment by aalexand** [comment]
There is https://github.com/google/pprof/blob/8596cd1e23a89ca2a93d4915897536d77a8e0256/internal/driver/driver_test.go#L39 ?

**Comment by Maaarcocr** [comment]
@aalexand omg, I'm super sorry, didn't notice this at all! Then, just ignore most of what I said and feel free to close the issue. 

I guess it would be beneficial for beginners (like me, as you may have probably guessed) if there was a very short README that informed contributors about this. Something like https://github.com/google/pprof/blob/master/internal/report/testdata/README.md
