### ISSUE TITLE
Compatibility with original pprof for remote profiling is broken (symbolization)

### ISSUE THREAD

**Issue by ErwanLegrand** [google/pprof#276]
### What version of pprof are you using?

Tested with Git revision 4b386c29ec7eb5d6227bae1e3e3c0c826d681389

### What operating system and processor architecture are you using?

Linux on AMD64

### What did you do?

I am trying to profile a remote server which implements the remote profiling protocol defined by gperftools (formerly Google Perftools): https://gperftools.github.io/gperftools/pprof_remote_servers.html

I used the following commands:
```
$ pprof -symbolize=remote https+insecure://XXX/pprof/profile
$ pprof -symbolize=remote https+insecure://XXX/pprof/heap
```
### What did you expect to see?

I expected profiling to succeed, as it does with the original (Perl) version of pprof.

### What did you see instead?
```
$ pprof -symbolize=remote https+insecure://XXX/pprof/heap
Fetching profile over HTTP from https+insecure://XXX/pprof/heap
pprof: http post https://XXX/symbolz: server response: 404 Not Found
```
Thus, the new pprof sends a request to /symbolz instead of /pprof/symbol as the original pprof did.

**Comment by aalexand** [comment]
I think the fix would be around https://github.com/google/pprof/blob/4b386c29ec7eb5d6227bae1e3e3c0c826d681389/internal/symbolz/symbolz.go#L67

Can you try changing that to check if the path ends with /pprof/profile or /pprof/heap and use /pprof/symbol in that case and see if that works?

**Comment by ErwanLegrand** [comment]
I thank you for the fast reply!

Indeed, I managed to make pprof request the expected /pprof/symbol URL with a simple change to this code.

But now I have another issue.
```
$ ~/go/src/github.com/google/pprof/pprof --symbolize=remote https+insecure://XXX/pprof/heap
Fetching profile over HTTP from https+insecure://XXX/pprof/heap
pprof: unexpected negative adjusted address, mapping &{4 0 18446744073709551615 0 https+insecure://root:admin@localhost:8080/pprof/heap  false false false false 0 0} source 18446744073709551615, offset 0
``` 

I do not know at this point whether the problem lies in the code of pprof or in the code of the server.

**Comment by aalexand** [comment]
/cc @rauls5382 who might have some thoughts.

The way it works is that

https://github.com/google/pprof/blob/a613757740614d4865db70ca9c80bc55cab3ab8f/internal/elfexec/elfexec.go#L174

is used to compute the offset to translate the virtual addresses in the code segment of the binary into the address that addr2line understands. For executables the offset is basically the delta between VirtAddr of the executable segment and the real virtual address of the executable segment used by the loader. In most cases for executables the offset should be zero, except with ASLR. Looks like something went wrong with the computation of that delta - pprof complains that after it applied the delta it got a negative address. It could also be that this address actually corresponds to one of shared objects in the process though, not executable.

**Comment by ErwanLegrand** [comment]
The executable is a PIE which makes sense, I believe, since it's a server. Thus, even the executable is relocated by ASLR. The request handler I have written takes care of this and use the actual memory mapping to perform symbol resolution. This works well with the old pprof.

I guess the problem here is the new pprof assumes the /pprof/symbol request handler will base its response on the default mapping while mine use the real mapping.

Perhaps I should open another issue as this is entirely unrelated to the original issue?

**Comment by aalexand** [comment]
Yes, perhaps open another issue for this. Would you mind preparing a pull request with a fix for the original issue?

**Comment by rauls5382** [comment]
The original pprof had only very limited ASLR support. You seem to be bypassing that and adjusting the addresses yourself. I suspect the new pprof is trying to adjust for ASLR after you've adjusted the addresses already, so we apply the adjustment twice and bad things happen.

Are you generating your profiles in profile.proto? For the new pprof I'd encourage you to generate your data in profile.proto, as the old format was not well specified.

**Comment by aalexand** [comment]
#280 was filed for the portion of this issue that is about the symbolization issues, closing this one which was about URL incompatibility.
