### ISSUE TITLE
Cannot open perf.data generated by Linux perf (regression)

### ISSUE THREAD

**Issue by navytux** [google/pprof#277]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

I'm on latest pprof from `github.com/google/pprof` (4b386c29ec) and on latest `github.com/google/perf_data_converter` (b86dd5276e)

### What operating system and processor architecture are you using?

`Linux deco 4.13.0-1-amd64 #1 SMP Debian 4.13.13-1 (2017-11-16) x86_64 GNU/Linux`

### What did you do?

I've tried to analyze `perf.data` generated by perf via pprof and it failed even though I have latest `perf_to_profile` on my path.

### What did you expect to see?

pprof loads profiling data from perf.data just ok, as readme says.

### What did you see instead?

```
$ perf record sleep 1
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.021 MB perf.data (7 samples) ]

$ pprof perf.data
Converting perf.data to a profile.proto... (May take a few minutes)
perf.data: failed to convert perf.data file. Try github.com/google/perf_data_converter: signal: aborted
pprof: failed to fetch any source profiles
```

--------

I've traced this down to the following:

- when seeing perf.data, pprof, before invoking perf_to_profile, creates temporary file for destination: https://github.com/google/pprof/blob/41ac4e1c/internal/driver/fetch.go#L532
- however perf_to_profile aborts when destination already exists: https://github.com/google/perf_data_converter/blob/b86dd5276e/perf_to_profile.cc#L35
https://github.com/google/perf_data_converter/blob/b86dd5276e/perf_to_profile.cc#L64
- it used not to be the case before
https://github.com/google/perf_data_converter/commit/48a540dd9376e37bb5edcc89ddd0715dcd867145#diff-183b816d357be307fcb59fc0a2fd2e03L71.

and indeed:

```
$ perf_to_profile perf.data out.pprof
[INFO:quipper/perf_reader.cc:847] Number of events stored: 185
[ERROR:quipper/perf_parser.cc:217] Unknown event type: 79
[INFO:perf_data_handler.cc:414] guessing main for pid: 13792 /bin/sleep
$ echo $?
0
$ perf_to_profile perf.data out.pprof
[INFO:quipper/perf_reader.cc:847] Number of events stored: 185
[ERROR:quipper/perf_parser.cc:217] Unknown event type: 79
[INFO:perf_data_handler.cc:414] guessing main for pid: 13792 /bin/sleep
File already exists: out.pprof
Aborted
$ echo $?
134
```

For now I'm working around this locally with the following a bit hacky patch to `perf_to_profile`:

```diff
diff --git a/perf_to_profile.cc b/perf_to_profile.cc
index 379cbb4..4753b44 100644
--- a/perf_to_profile.cc
+++ b/perf_to_profile.cc
@@ -32,7 +32,7 @@ string ReadFileToString(const char* path) {
 void CreateFile(const char* path, std::ofstream* file) {
   if (FileExists(path)) {
     std::cerr << "File already exists: " << path << std::endl;
-    abort();
+    //abort();
   }
   file->open(path);
   if (!file->is_open()) {
```

Thanks beforehand,
Kirill

P.S. reporting to pprof because https://github.com/google/perf_data_converter/ has issues disabled.

/cc @cjiang, @wade-k

**Comment by aalexand** [comment]
@lannadorai I think you had a fix for this recently?

**Comment by aalexand** [comment]
@navytux I've enabled the issues in the https://github.com/google/perf_data_converter/ repo fwiw.

**Comment by navytux** [comment]
@aalexand thanks for feedback and for enabling issues there.

**Comment by lannadorai** [comment]
@navytux @aalexand I'm working on the fix.

**Comment by navytux** [comment]
@lannadorai good luck & thanks for feedback.

**Comment by aalexand** [comment]
@lannadorai What's the fix status?

**Comment by aalexand** [comment]
@lannadorai Any updates? If you still work on adding a test, I'd suggest getting the fix in and filing another issue on adding the test, WDYT?
