### ISSUE TITLE
Misleading error messages when using bad values with 'granularity' and other options

### ISSUE THREAD

**Issue by ALTree** [google/pprof#293]
### What version of pprof are you using?

I'm at e9167955d76d4625c2309f3e02881f4424173440

### What operating system and processor architecture are you using?

Linux/amd64

Certain options print a reasonable error message when they're used incorrectly. For example, `sample_index`

```
(pprof) sample_index = 0      # works

(pprof) sample_index = 7      # bad value
sample_index 7 is outside the range [0..3]
```

And with the verbose option name:

```
(pprof) sample_index = alloc_space  # works

(pprof) sample_index = wrong        # bad value
sample_index "wrong" must be one of: [alloc_objects alloc_space inuse_objects inuse_space]
```

Other options, like `granularity`, print a misleading error message when used incorrectly. Example:

```
(pprof) granularity = lines      # works

(pprof) granularity = wrong      # bad value
Unrecognized command: "granularity"
```

The error message says `Unrecognized command: "granularity"` which is wrong and misleading.

**Comment by aalexand** [comment]
@nolanmar511 PTAL

@ALTree  I am renaming the issue to be more specific about the issue described. If there are other examples of confusing error messages, please outline them.

**Comment by ALTree** [comment]
This is not just for `granularity`. At the moment I don't have time to try all of them but I can tell you there are at least two because `cumulative` has the same issue

```
(pprof) cumulative = flat
(pprof) cumulative = wrong
Unrecognized command: "cumulative"

```

**Comment by nolanmar511** [comment]
I'll look through the commands and find those with misleading errors.

**Comment by ALTree** [comment]
@nolanmar511 thanks!

**Comment by nolanmar511** [comment]
@ALTree  -- To confirm, the misleading error messages you are referring to only happen when using the interactive shell?

If that's the case, then, I believe this problem only impacts `cumulative` and `granularity`. Or more generally, any command line options which are declared like this, where the 3rd value for `variable` is not the empty string:

```
	"flat": &variable{boolKind, "t", "cumulative", helpText("Sort entries based on own weight")},
	"cum":  &variable{boolKind, "f", "cumulative", helpText("Sort entries based on cumulative weight")},
```

**Comment by ALTree** [comment]
> To confirm, the misleading error messages you are referring to only happen when using the interactive shell?

Yes.
