### ISSUE TITLE
Random port doesn't work

### ISSUE THREAD

**Issue by Timmmm** [google/pprof#307]
The readme says if you use `-http=":"` it will run on a random port, but actually you just get a parse error due to [this code](https://github.com/google/pprof/blob/80fc05d9036b19d9903eb19b0fb8aca62af01f8a/internal/driver/webui.go#L90).

    pprof: invalid port number: strconv.Atoi: parsing "": invalid syntax

**Comment by nolanmar511** [comment]
I've looked a bit at this. Can reproduce. 
The code has been restructured somewhat since that functionality has worked -- openBrowser is called before net.Listen() (which, I believe, had been used to select the port).
