### ISSUE TITLE
Run dsymutil on OSX

### ISSUE THREAD

**Issue by Timmmm** [google/pprof#310]
On OSX there is some debug info in `.dSYM` folders which is generated lazily (by running `dsymutil <binary>`). If you don't do this `llvm-symbolizer` can't find the file names and line numbers of any addresses. The graph views (e.g. `-web`) still work, but source views (`-weblist`) do not.

It would be good if pprof could run this automatically or at least warn about it. Would be worth checking what `lldb` does in this situation.

**Comment by aalexand** [comment]
It seems a bit strange to me if every tool like pprof that wants to consume debug symbol information for a binary needs to invoke `dsymutil` before attempting that. Reading https://stackoverflow.com/a/32299029/848626 it appears that having the build run dsymutil as part of post-link stage is what needs to be done?

**Comment by aalexand** [comment]
I feel that pprof should just assume the presence of the debug information and the user should make sure it's there. Trying to detect the absence of it seems a bit too far for a simple tool like pprof imo. I'm closing this, will re-open if there is future evidence it's worth it.

**Comment by SolomidHero** [comment]
I prefer the solution where pprof tells at least if binary or some dynamic library in dependencies requires debug symbols information, since otherwise visualisation is usually useless (it shows a lot of unnamed addresses)
