### ISSUE TITLE
Fails with shared libraries because mapping is ignored on OSX

### ISSUE THREAD

**Issue by Timmmm** [google/pprof#311]
See [this issue](https://github.com/gperftools/gperftools/issues/956) for background and test case.

Basically on OSX pprof does not subtract the mapped base address of shared libraries from code addresses before feeding them to `llvm-symbolizer`.

I don't know exactly how it is supposed to work, but replacing [this line](https://github.com/google/pprof/blob/master/internal/symbolizer/symbolizer.go#L164) with this seems to make it work:

```
		addr := l.Address
		if l.Mapping != nil {
			addr -= l.Mapping.Start
		}

		stack, err := segment.SourceLine(addr)
```

Also, for some very strange reason, with this patch, `-web`, `-top` and `-list '.*'` work but `-weblist '.*'` does not. However `-weblist 'factorial'` *does* work. It seems like the web interface trips up on the first `??` output:

```
$ pprof -list ".*" out.prof
Local symbolization failed for libdyld.dylib: unrecognized binary: /usr/lib/system/libdyld.dylib
Some binary filenames not available. Symbolization may be incomplete.
Try setting PPROF_BINARY_PATH to the search path for local binaries.
Total: 690ms
ROUTINE ========================  in ??
         0      690ms (flat, cum)   100% of Total
 Error: Could not find file ?? on path /Users/me/test
ROUTINE ======================== factorial in /Users/me/test/lib.cpp
     690ms      690ms (flat, cum)   100% of Total
         .          .      3:    long long int result=m_nValue;
         .          .      4:    long long int result_next;
         .          .      5:    long long int pc = m_nValue;
         .          .      6:    do
         .          .      7:    {
     310ms      310ms      8:        result_next = result*(pc-1);
     250ms      250ms      9:        result = result_next;
      60ms       60ms     10:        pc--;
      70ms       70ms     11:    } while(pc>2);
         .          .     12:    m_nValue = result;
         .          .     13:    return m_nValue;
         .          .     14:}
         .          .     15:
         .          .     16:int foo() {
```

**Comment by aalexand** [comment]
Huh, thanks a lot for tracking this down, this makes a lot of sense. I think your fix will also help a number of cases people had in #130 - some of symbolization issues mentioned there are with dynamic libraries and some could have been because of executable's ASLR.
