### ISSUE TITLE
Show coverage counts in source code view

### ISSUE THREAD

**Issue by Timmmm** [google/pprof#314]
`llvm-cov` can generate nice coverage profiles (line execution counts) that look like this:

![image](https://user-images.githubusercontent.com/376842/35872129-ee1574c6-0b5d-11e8-97bf-ddd2a39fd117.png)

And `pprof` can make nice sample-based profile views like this:

![image](https://user-images.githubusercontent.com/376842/35872201-2240b4d6-0b5e-11e8-9575-5440562f0b9b.png)

These are just begging to be merged. Then you can calculate the average time per execution. Maybe this is already possible, but I couldn't see how.

**Comment by aalexand** [comment]
There is `-mean` flag in pprof that makes it divide the currently displayed metric (chosen by `-sample_index` flag) by the first metric in the profile. So if there would be a tool to generate a profile proto out of llvm-cov data, and there would be a way in pprof to merge two profiles by putting their metrics side by side, then something like `pprof -mean -sample_index=cpu llvm-cov.profile my-cpu.profile` would probably just work.

**Comment by Timmmm** [comment]
I had a brief look into this and unfortunately it doesn't seem trivial. The profile produced by the LLVM-instrumented binaries has data something like this (`llvm-profdata -text`):

```

_ZNSt3__19addressofIKcEEPT_RS2_
# Func Hash:
0
# Num Counters:
1
# Counter Values:
0

_Z9factorialx
# Func Hash:
3
# Num Counters:
2
# Counter Values:
19999
199930006
```

That is, for each basic block there is a counter, and it just stores the value of the counter. To find the source lines of the basic block that each counter corresponds to it reads the executable in some way.

Also I'm not exactly sure how I would save the per-line information in the `profile.proto` format.

**Comment by aalexand** [comment]
Closing since we don't expect to work on this soon.
