### ISSUE TITLE
URL path /debug/pprof does not list all the available choices

### ISSUE THREAD

**Issue by MikeSpreitzer** [google/pprof#333]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

Whatever is in the Docker image `quay.io/coreos/hyperkube:v1.8.7_coreos.0`.

Here is a possibly informative entry from its `/metrics`:

kubernetes_build_info{buildDate="2018-01-18T00:17:18Z",compiler="gc",gitCommit="768e049ab5230010251f30475e0e785e2e999566",gitTreeState="clean",gitVersion="v1.8.7+coreos.0",goVersion="go1.8.3",major="1",minor="8+",platform="linux/amd64"}

If you are using pprof via `go tool pprof`, what's your `go env` output?
If you run pprof from GitHub, what's the Git revision?

### What operating system and processor architecture are you using?

That is a Docker container image.  I ran it on Ubuntu 16.04.1, on an Intel processor.

### What did you do?

`kubectl get --raw /debug/pprof --server https://10.233.110.91 --insecure-skip-tls-verify`

If possible, provide a recipe for reproducing the error.
Attaching a profile you are trying to analyze is good.

### What did you expect to see?

I expected to see the complete list of `<foo>` that makes for a valid path `/debug/pprof/<foo>`.

BTW, I can not find the complete list in any one place.  Different partial lists can be found: as shown here, in https://golang.org/pkg/net/http/pprof/ , in https://raywangblog.wordpress.com/2017/07/16/golang-profiling/ , and in https://blog.golang.org/profiling-go-programs .

### What did you see instead?

Fetching `/debug/pprof` got me the following list of choices:
```
<tr><td align=right>0<td><a href="block?debug=1">block</a>
<tr><td align=right>64<td><a href="goroutine?debug=1">goroutine</a>
<tr><td align=right>18<td><a href="heap?debug=1">heap</a>
<tr><td align=right>0<td><a href="mutex?debug=1">mutex</a>
<tr><td align=right>15<td><a href="threadcreate?debug=1">threadcreate</a>
```

Astonishingly, `profile` is missing from that list!  So is `trace` (which _is_ mentioned in https://golang.org/pkg/net/http/pprof/ --- which, distressingly, does not say anything about `?debug=1`).

**Comment by dgryski** [comment]
This bug should be opened against the `net/http/pprof` package in the Go tracker.

**Comment by nolanmar511** [comment]
I'm closing this, since this issue can be re-routed (to net/http/pprof package in the Go tracker, as mentioned by dgryski), and this change is not pprof scoped.
