### ISSUE TITLE
/debug/pprof should offer a way to call SetMutexProfileFraction

### ISSUE THREAD

**Issue by MikeSpreitzer** [google/pprof#334]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

This is a request for a feature that does not yet exist.

If you are using pprof via `go tool pprof`, what's your `go env` output?
If you run pprof from GitHub, what's the Git revision?

### What did you do?

I fetched `/debug/pprof/mutex` from a running Kubernetes apiserver.

If possible, provide a recipe for reproducing the error.
Attaching a profile you are trying to analyze is good.

### What did you expect to see?

I hoped to see something useful.

### What did you see instead?

I got an empty profile.  Because the Kubernetes apiserver does not call http://beta.golang.org/pkg/runtime/#SetMutexProfileFraction .  In fact, it would not be ideal to run with a non-zero fraction all the time.  I would like to be able to turn on mutex contention sampling for a while, then fetch the profile, then turn off sampling.

**Comment by aalexand** [comment]
There is a related discussion in https://github.com/golang/go/issues/23401. This is golang feature request as there are runtime costs to this, so not pprof scoped.
