### ISSUE TITLE
TestMachoFiles failing on darwin/amd64

### ISSUE THREAD

**Issue by mvdan** [google/pprof#342]
This took down the three darwin/amd64 builders, as one can see on https://build.golang.org/ (fixed by the vendor update revert).

https://build.golang.org/log/090018bcc232072f53ddc7750e24f42f52e79719
https://build.golang.org/log/1cbedd8b8b11d1baadcbfabcf8d8809ece5ab307
https://build.golang.org/log/81fd8501a182718b4e87ffd66d36d7e9c9034e6a

The actual failure:

```
--- FAIL: TestMachoFiles (0.12s)
    --- FAIL: TestMachoFiles/normal_mapping (0.10s)
    	binutils_test.go:316: SourceLine for main: got [{_main  0}]; want [{main /tmp/hello.c 3}]
    --- FAIL: TestMachoFiles/other_mapping (0.01s)
    	binutils_test.go:316: SourceLine for main: got [{_main  0}]; want [{main /tmp/hello.c 3}]
    --- FAIL: TestMachoFiles/lib_normal_mapping (0.01s)
    	binutils_test.go:316: SourceLine for main: got [{_bar  0}]; want [{bar /tmp/lib.c 5}]
FAIL
FAIL	cmd/vendor/github.com/google/pprof/internal/binutils	0.170s
```

The failures happened when we updated to the following commit: 20ceacaff62f6bf3e7c08128ea03d6faa84c880c

Funnily enough, that commit enables the very test that is failing.

/cc @aalexand @nolanmar511 who authored and committed said commit.

**Comment by aalexand** [comment]
Most likely the builder environment doesn't have gaddr2line or llvm-symbolizer available in PATH.

**Comment by mvdan** [comment]
I assume then that the test should be skipped if the tools aren't installed?

**Comment by mvdan** [comment]
@aalexand any update on this issue? We'd like to update our vendored copy to import the other two flake issue fixes, but this failure is blocking us. We can always re-vendor and manually disable the test, but that's a bit suboptimal.

**Comment by aalexand** [comment]
#352 should fix it.

**Comment by mvdan** [comment]
Awesome, thank you! Will update the vendored pprof now.
