### ISSUE TITLE
Could not save profile: protocol error (trying to use pprof inside docker image golang:1.7-alpine)

### ISSUE THREAD

**Issue by veqryn** [google/pprof#36]
I am attempting to use pprof inside of the docker container image `golang:1.7-alpine`.

This is the error I get:
```
bash-4.3# go tool pprof -svg -output=/pprof.svg http://host:port/debug/pprof/heap
Fetching profile from http://host:port/debug/pprof/heap
Could not save profile: open /root/pprof/pprof.host:port.inuse_objects.inuse_space.001.pb.gz: protocol error
Generating report in /pprof.svg
bash-4.3#
```

The svg file seems to work fine, but the pb.gz file is not created.

I've tried installing things, including protobuf, graphviz, gzip, etc.
Not sure what is missing or needed, or why this error is occurring.

**Comment by rauls5382** [comment]
go tool pprof is not this version of pprof, but the one from the Go distribution (which is based on an old version of this one). Neither one depends on protobuf, graphviz, or gzip.

I suspect a problem with the filesystem that holds /root/pprof. Try generating the profile directly in profile.proto format:

go tool pprof -proto -output=/tmp/pprof.pb.gz http://host:port/debug/pprof/heap

**Comment by veqryn** [comment]
Yes, it appears to be an issue with the `:` in the file name that gets auto-generated.  Removing that solved the issue.  Thanks!
