### ISSUE TITLE
Should we support legacy convenience options (i.e. inuse_objects) from interactive pprof?

### ISSUE THREAD

**Issue by nolanmar511** [google/pprof#378]
Right now, we can't use legacy convenience options in interactive mode.

For exampe:
```
(pprof) inuse_objects
Unrecognized command: "inuse_objects"
```

Instead, you have to specify `sample_index=inuse_objects`.

Do we want to change this?

Alternatively, we can improve the documentation.

**Comment by aalexand** [comment]
Discussed, we tend to say no, it's not needed. Closing until we get more requests / complaints on this.
