### ISSUE TITLE
Make Profile.serialize() a public method

### ISSUE THREAD

**Issue by chyeh** [google/pprof#385]
Hello, I'm wondering if there's any possibility that [`serialize()`](https://github.com/google/pprof/blob/1ddc9e21322e23449cb6709652bf3583969ca167/profile/profile.go#L309) will be a public method. The reason I propose this idea is because in my scenario I need to know the length of the serialized profile, which is a `[]byte` type variable, before writing. It will also be easier to integrate with objects of the `io.Writer` interface since the `Writer.Write()` method takes an argument of `[]byte` type .

**Comment by aalexand** [comment]
Can you give an example of pseudo-code you would have with call to Serialize? I am trying to understand why you can't use Write or WriteSerialized and use Len() to know the size of the serialized data.

**Comment by chyeh** [comment]
@aalexand Thanks for your quick reply! I didn't know there is the `WriteSerialized()` method in this package. I couldn't find it in the [godoc page](https://godoc.org/github.com/google/pprof/profile) Where is that?

**Comment by aalexand** [comment]
Sorry, I meant Write or WriteUncompressed.

**Comment by chyeh** [comment]
I was actually trying to write `Profile` objects into a `.tar` file. However, it requires writing the tar header before the serialized data and it needs the length of the serialized data in the tar header.

```
var body []byte
//...
p, err := profile.Parse(bytes.NewReader(body))
//...
serializedData := p.Serialize()

header := &tar.Header{
  Name: "profileName",
  Mode: 0644,
  Size: int64(len(serializedData)),
}
if err := tw.WriteHeader(header); err != nil {
  panic(err)
}
if _, err := tarWriter.Write(serializedData); err != nil {
  log.Fatal(err)
}
```

**Comment by aalexand** [comment]
Why not
```
var buf bytes.Buffer
if err := p.Write(&buf); err != nil {
  return err
}

header := &tar.Header{
  Name: "profileName",
  Mode: 0644,
  Size: int64(buf.Len()),
}
if err := tarWriter.WriteHeader(header); err != nil {
  return err
}
if _, err := tarWriter.Write(buf.Bytes()); err != nil {
  return err
}
```

**Comment by chyeh** [comment]
I didn't think about this! Thank you!
