### ISSUE TITLE
Deal with deleted binaries more carefully

### ISSUE THREAD

**Issue by mkevac** [google/pprof#386]
### What version of pprof are you using?

8b03ce837f3401233d4e32de3a5f0ea3ff1c13c2 from github

### What operating system and processor architecture are you using?

Ubuntu 18.04 LTS
4.15.0-22-generic

### What did you do?

Tried to profile remote binary with command
```
$ pprof -http=:8080 foobar.lan:31571/debug/pprof/profile?seconds=5
```

### What did you see?

```
$ pprof -http=:8080 foobar.lan:31571/debug/pprof/profile?seconds=5
Fetching profile over HTTP from http://foobar.lan:31571/debug/pprof/profile?seconds=5
Local symbolization failed for foobar-3.61.0-4290 (deleted): stat /local/foobar/bin/foobar-3.61.0-4290 (deleted): no such file or directory
Some binary filenames not available. Symbolization may be incomplete.
Try setting PPROF_BINARY_PATH to the search path for local binaries.
Saved profile in /home/marko/pprof/pprof.foobar-3.61.0-4290 (deleted).samples.cpu.002.pb.gz
```

### What did you expect to see?

Error that didn't have "(deleted)" in the path. And saved profile that didn't have "(deleted)" in the path.
I think that pprof should remove "(deleted)" from file path.

### Where did this (deleted) come from?

If you remove or change binary file for running program, you get this line in maps:

```
marko@foobar.lan:~> sudo head -n 3 /proc/6102/maps
00400000-00d0b000 r-xp 00000000 fe:02 48234504                           /local/foobar/bin/foobar-3.61.0-4290 (deleted)
00f0a000-00f10000 r--p 0090a000 fe:02 48234504                           /local/foobar/bin/foobar-3.61.0-4290 (deleted)
00f10000-00f58000 rw-p 00910000 fe:02 48234504                           /local/foobar/bin/foobar-3.61.0-4290 (deleted)
```

There is a similar problem in linux perf utility :-)

**Comment by aalexand** [comment]
This seems like a rather exotic scenario - why would anyone delete the profiled binary before the analysis is done in practice?

**Comment by mkevac** [comment]
I don't think it's exotic. Imagine you have a running service and it's been running for 1 month. Anything could have happened in this month.
Someone could have deleted the binary manually. Puppet, Ansible, etc could have deleted it or moved or rewritten it.

**Comment by rauls5382** [comment]
I think if some postprocesing of the maps file were to be done it should be on the profile source, not on pprof. Is this from Go, C++ with gperftools, or something else?

**Comment by mkevac** [comment]
It is from Go (net/http/pprof).

**Comment by rauls5382** [comment]
+@hyangah for a golang opinion. Could this be handled in golang?

**Comment by hyangah** [comment]
@rauls5382 What does other language do to encode the mapping info? Is it an issue unique to Go  because Go acquires the info through /proc/self/maps? If other languages may encounter the same issue, probably it's better to handle that from the tool.

BTW why does the pprof tool attempt to perform local symbolization in this case? The binary may not exist there, so local symbolization will fail even with a cleaned up filename. 

One thing to note: Go retrieves the info for the build_id field by reading the binary. If the binary was deleted, the build id will remain empty.

**Comment by mkevac** [comment]
> BTW why does the pprof tool attempt to perform local symbolization in this case? The binary may not exist there, so local symbolization will fail even with a cleaned up filename.
Yes, but I could put file locally. It is strange to name it "blabla (deleted)" though :-)

**Comment by rauls5382** [comment]
pprof will attempt local symbolization if remote symbolization fails.

Other profile producers may collect the binary name through other means. Clearly this isn't unique to Go: as mkevac points out Linux perf runs into the same issue, but I wouldn't want to add special cases to pprof to handle weirdness from some platforms. I believe these should be handled at source, or we will end up with an unwieldy set of special case handling in pprof.

I do agree that this is perhaps a minor issue, as it is a corner case and pprof does allow a rudimentary mechanism to override the binary name (by passing a filename to the command line).

mkevac, I think if you want to pursue you should open a bug against golang. Closing for now.
