### ISSUE TITLE
pprof is unmarshaling profile data in a way that only works for same-endian files

### ISSUE THREAD

**Issue by joejulian** [google/pprof#387]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

git rev: 4d67f66d7c9469639518a80f378434bb7e9156b7

### What operating system and processor architecture are you using?

linux when you combine arm64 generated perf data and amd64 pprof.

### What did you do?

I created an arm64 binary that needed profiling, ie.
```
import "github.com/pkg/profile"

main() {
  defer profile.Start(profile.CPUProfile).Stop()
  # do something
}
```

Created the cpu.prof and copied it to an amd64 box. Ran pprof against it.

### What did you expect to see?
I expected to be able to read the data.

### What did you see instead?
```
$ pprof --text kube-apiserver ~/cpu.pprof         
Using local file kube-apiserver.
Using local file /home/jjulian/cpu.pprof.
/home/jjulian/cpu.pprof: not a profile file, or old format profile file
```

### Note:
This problem was fixed in the original perl code: https://github.com/gperftools/gperftools/commit/49237462c8ae7920332c1034c623e57b50a6109c

**Comment by rauls5382** [comment]
I believe pprof has code to handle endianness. Perhaps it is being defeated.
Can you attach a sample non-confidential profile?

**Comment by joejulian** [comment]
[cpu.pprof.gz](https://github.com/google/pprof/files/2073340/cpu.pprof.gz)

**Comment by rauls5382** [comment]
It seems your file has been gzipped twice. After gzipping it pprof has no trouble processing it.

This should work:
mv cpu.pprof.gz cpu.pprof.gz.gz
gunzip cpu.pprof.gz.gz
pprof cpu.pprof.gz

**Comment by joejulian** [comment]
Github wouldn't allow the .pprof extension to be uploaded so I gzipped it, not even realizing it's compressed by default.

**Comment by rauls5382** [comment]
My point is that pprof supports endianness and can handle your file after gzipping it.
Looking at your report again it seems you're using the ancient pprof version from gperftools.

Please use the version of pprof from github.com/google/pprof or from the Go distribution.

**Comment by joejulian** [comment]
I understand your expectation, unfortunately that's not what happened. It failed and didn't handle my file when transferred between architectures. 

The second layer of gzip was done to satisfy github's requirements. It's an irrelevant detail.

I simply mentioned the perl code because they'd had to fix the endian issue and I was hoping it would be useful as a reference. If I'd been using that code, I would not have filed an issue here.

**Comment by joejulian** [comment]
btw... when I built pprof for arm64 and copied it to my Raspberry Pi, _that_ version _was_ able to read the cpu.pprof.

**Comment by joejulian** [comment]
both were built at the same commit, 4d67f66d7c9469639518a80f378434bb7e9156b7

**Comment by rauls5382** [comment]
Can you show the output that you get from the new pprof? It did work for me on an amd64 system.
The output you listed on the "What did you see instead?" section seems to be from the old pprof.

**Comment by joejulian** [comment]
Got it... Sorry, you're right of course. Stupid $PATH... :)
