### ISSUE TITLE
Is it worth it supporting Go 1.7 and 1.8?

### ISSUE THREAD

**Issue by aalexand** [google/pprof#398]
@rauls5382 @nolanmar511 @hyangah for your thoughts

The recent Travis CI builds for pprof on Github [fail](https://travis-ci.org/google/pprof/jobs/402490958) with an error like

```
$ go get -u github.com/golang/lint/golint honnef.co/go/tools/cmd/...
# honnef.co/go/tools/lint/lintutil
../../../honnef.co/go/tools/lint/lintutil/util.go:273: undefined: types.SizesFor
```

The error is on the builds for Go 1.7 and 1.8.

This tool is a lint tool the CI build uses, so a simple fix is to only run the linter check on the builds for more recent Go version.

But I wonder if we can just stop supporting Go 1.7 and 1.8? Is there any practical need for that?

**Comment by aalexand** [comment]
This is the comment that says the lint tool only supports current and previous versions of Go: https://github.com/dominikh/go-tools/issues/296#issuecomment-403927504

**Comment by rsc** [comment]
The Go project only supports the two most recent major releases (https://golang.org/doc/devel/release.html). Right now that's Go 1.9 and Go 1.10. I don't see why pprof would need to support older versions.
