### ISSUE TITLE
Support Intel syntax in the assembly reports

### ISSUE THREAD

**Issue by aalexand** [google/pprof#400]
A user asked for this. Filing so that other users can upvote.

There is a workaround of creating a script, say ~/bin/objdump with content

```
#!/bin/bash
/usr/bin/objdump -M intel $*
```

and then setting

```
export PPROF_TOOLS=objdump:/home/user/bin/
```

but this is somewhat cumbersome.

**Comment by wyk9787** [comment]
Should this be added as an independent option that only applies to "-disasm" and "-weblist" or as a parameter taken by those two commands?

**Comment by aalexand** [comment]
Independent option I think. It's not special / important enough to be a dedicated argument for those commands.
