### ISSUE TITLE
pprof -web opens an svg image on my linux machine

### ISSUE THREAD

**Issue by nolanmar511** [google/pprof#402]
### What version of pprof are you using?
3e1e08e68eaed0faefa67fe1c1e10e004cec2c9a (latest commit at the time of posting this)

If you are using pprof via `go tool pprof`, what's your `go env` output?
If you run pprof from GitHub, what's the Git revision?

### What operating system and processor architecture are you using?
Linux (ubuntu)

### What did you do?
I called `pprof -web /path/to/profile.pb.gz`

### What did you expect to see?
I expected the graph to open in chrome.

### What did you see instead?
An svg image opened.

I think this is related to https://github.com/google/pprof/pull/392

**Comment by aalexand** [comment]
The agreement is that -web should open the SVG file in the browser. Let's roll back #392 if necessary.
