### ISSUE TITLE
Showing relationship between functions in text form output

### ISSUE THREAD

**Issue by tngan** [google/pprof#403]
Is it desired to do that in text form? For example by appending the prefix of its parent function name, then I can use the output to customize graph form output.

**Comment by tngan** [comment]
Thanks for your quick response. The steps I generated for the profile as followed.

```console
LD_PRELOAD=/usr/lib/libprofiler.so CPUPROFILE=/tmp/geany.prof geany

google-pprof --text /usr/bin/geany /tmp/geany.prof > profile_text
```

In the generated `profile_text`, I can see the information.

```
Total: 390 samples
      20   5.1%   5.1%       20   5.1% g_unix_fd_add
      18   4.6%   9.7%       18   4.6% g_spawn_close_pid
      12   3.1%  12.8%       12   3.1% _int_malloc
      10   2.6%  15.4%       10   2.6% __poll
      10   2.6%  17.9%       10   2.6% g_type_check_instance_is_a
      10   2.6%  20.5%       10   2.6% g_type_value_table_peek
       9   2.3%  22.8%        9   2.3% __GI___libc_malloc
...
```

I have figured out how to interpret the columns as mentioned in this [document](https://gperftools.github.io/gperftools/cpuprofile.html).

> Here is how to interpret the columns:
> 
> Number of profiling samples in this function
> Percentage of profiling samples in this function
> Percentage of profiling samples in the functions printed so far
> Number of profiling samples in this function and its callees
> Percentage of profiling samples in this function and its callees
> Function name

However, in accordance of the document, there is no explicit way to deduce the function relationship from the text form output. My question is that is it possible to enhance the text form output with additional information specifying the caller/callee relationship between the functions.

**Comment by aalexand** [comment]
Look at "pprof -help", there are many output formats and many of them visualize the function caller-callee relationship. For example, try "-graphviz" or "-tree".

By the way, your instructions use "google-pprof" as the tool name, make sure you use the pprof that comes from this repo, not the old one that you may have gotten with gperftools.

**Comment by tngan** [comment]
@aalexand Thanks for your reply, I will check it out.
