### ISSUE TITLE
`go tool pprof` is using lot of memory when tried to load mem.pprof file

### ISSUE THREAD

**Issue by nilsocket** [google/pprof#407]
### What version of Go are you using (`go version`)?
`go version go1.10.3 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
kernel=`4.17.11-arch1`

### What did you do?
Wrote a [mergeSort program](https://play.golang.org/p/gLQfPaEz6ii), which uses a lot of memory (4 to 5GB),
for an input of one hundred million numbers.
Switched on memory profiling, which produced a pprof file of size 12.3MB.
Tried to load with `go tool pprof mem.pprof`.
> I knew there were some mistakes in the above mentioned program.

### What did you expect to see?
I expected `go tool` to not take lot of memory.

### What did you see instead?
`go tool` is taking lot of memory(4 to 5GB), while loading this [mem.pprof](https://drive.google.com/open?id=1q1NZO3XPLK79bmXf619vDYBHJ3ciehya) file.

### Is this reproducible?
Yes, I tried to load the same file in another laptop, which is running `Ubuntu 16.04`, with same go version.
kernel=`4.4.0-131-generic`
Same result.

> Don't load this file if you have less than 6GB of free memory.

**Comment by nolanmar511** [comment]
The amount of memory that pprof is using in this case may be unexpected, but I'm actual not particularly surprised. 12.3MB is a big profile. This profile when uncompressed is 80mB, so not only is this a large profile, it's a large profile which was compressed fairly well compared to other large profiles. The raw text dump of this profile is 100 GB.

How did you collect this profile? I'm curious as to why it's so large.

**Comment by nilsocket** [comment]
Input is hundred million random numbers.
I was also creating a new slice for each merge.

**Comment by aalexand** [comment]
@nolanmar511 I think the profile is collected using the linked program - https://play.golang.org/p/gLQfPaEz6ii. @nilsocket Can you share the input file as well so that there is exact reproducer?

@nolanmar511 The raw text dump probably has a lot of duplication like same string is printed over and over again. There shouldn't be this duplication in memory I think since Go strings are immutable and would be shared in memory. It would be good to add something like `defer profile.Start(profile.MemProfile).Stop()` to pprof main, reproduce the problem and see where the memory goes. I wonder if it has to do with the handling of tags.

**Comment by nilsocket** [comment]
Input file size 847MB, I can't upload it now, because I don't have that
much data left in my data-pack.
By the way my internet is too slow, it took 3 minutes to open and download
a subtitle file.

I will upload tomorrow morning as soon as I go to office.

Input is hundred million random numbers, generated with rand.Intn() long
back and saved to a file.

**Comment by aalexand** [comment]
@nolanmar511 OK, you could probably just generate such file with 1e7 random numbers using rand.Intn() yourself.

**Comment by rsc** [comment]
This is kind of a worst case for pprof. Pprof assumes that there won't be too many unique call stacks, but here the recursive calls trace out a binary tree of different call stacks, with a different stack for every array index, and the program spends equal time at each leaf in the tree. If there are N inputs then there are also O(N) - around N/4 - allocation-site call stacks. Sampling eliminates a fraction of them but there are still quite a lot left.

**Comment by nilsocket** [comment]
Here is the [file](https://drive.google.com/open?id=1DZ9BEOAL2nyOYnv1Yzx9z7b_6ubrerrQ), if necessary.
If you are generating by yourself, don't forget to add the count of integers, in the first line.i.e.,
if input is 3 random integers.
`3 89 56 77`

**Comment by aalexand** [comment]
@nilsocket The best way to make the resulting profile smaller for this program would be to get rid of recursion, if possible.

**Comment by aalexand** [comment]
I think this program is a bit synthetic corner case, so I am not sure it's worth keeping the issue open. Please re-open if anybody feels it's worth a closer look.
