### ISSUE TITLE
Discrepency between pprof list and weblist

### ISSUE THREAD

**Issue by ardan-bkennedy** [google/pprof#415]
### What version of Go are you using (`go version`)?
```go version go1.11 darwin/amd64```

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bill/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bill/code/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p6/l5y36lvx3zvdc3gtfh0g_43w0000gn/T/go-build393058492=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

Using this code:
https://github.com/ardanlabs/gotraining/tree/master/topics/go/profiling/memcpu

I ran this set of commands:
```
$ go test -gcflags "-m -m" -run none -bench . -benchtime 3s -benchmem -memprofile p.out  
$ go tool pprof p.out  
(pprof) weblist algOne  
```

### What did you expect to see?

I saw the `weblist` view was different (and more accurate) then the `list` view

**weblist view**
```
Type: alloc_space
Time: Sep 3, 2018 at 10:39am (PDT)
Total: 325.53MB
github.com/ardanlabs/gotraining/topics/go/profiling/memcpu.algOne
/Users/bill/code/go/src/github.com/ardanlabs/gotraining/topics/go/profiling/memcpu/stream.go

  Total:    325.53MB   325.53MB (flat, cum)   100%
     78            .          .            
     79            .          .           // algOne is one way to solve the problem. 
     80            .          .           func algOne(data []byte, find []byte, repl []byte, output *bytes.Buffer) { 
     81            .          .            
     82            .          .           	// Use a bytes Buffer to provide a stream to process. 
     83     311.03MB   311.03MB           	input := bytes.NewBuffer(data) 
     84            .          .            
     85            .          .           	// The number of bytes we are looking for. 
     86            .          .           	size := len(find) 
     87            .          .            
     88            .          .           	// Declare the buffers we need to process the stream. 
     89      14.50MB    14.50MB           	buf := make([]byte, size) 
     90            .          .           	end := size - 1 
     91            .          .            
     92            .          .           	// Read in an initial number of bytes we need to get started. 
     93            .          .           	if n, err := io.ReadFull(input, buf[:end]); err != nil { 
     94            .          .           		output.Write(buf[:n]) 
```

**list view** . 
```
ROUTINE ======================== github.com/ardanlabs/gotraining/topics/go/profiling/memcpu.algOne in /Users/bill/code/go/src/github.com/ardanlabs/gotraining/topics/go/profiling/memcpu/stream.go
   14.50MB   325.53MB (flat, cum)   100% of Total
         .          .     78:
         .          .     79:// algOne is one way to solve the problem.
         .          .     80:func algOne(data []byte, find []byte, repl []byte, output *bytes.Buffer) {
         .          .     81:
         .          .     82:	// Use a bytes Buffer to provide a stream to process.
         .   311.03MB     83:	input := bytes.NewBuffer(data)
         .          .     84:
         .          .     85:	// The number of bytes we are looking for.
         .          .     86:	size := len(find)
         .          .     87:
         .          .     88:	// Declare the buffers we need to process the stream.
   14.50MB    14.50MB     89:	buf := make([]byte, size)
         .          .     90:	end := size - 1
```

### What did you see instead?

Notice the `weblist` view is showing the allocation is flat, which is correct since the call to NewBuffer is inlined. Maybe more important the views are different. Please keep the allocation `flat` on the report, because it is more accurate with what the compiler chose to do.

**Comment by aalexand** [comment]
I don't know of a good reason to collapse the inlined locations for `weblist` but not for `list`. Similarly, I am not sure why the node count threshold is only reset for `list`. @rauls5382 ?

If there isn't a good reason for the current behavior I'd suggest introducing "linesnoinlines" granularity and use that for the `list` command, as well as remove resetting `nodecount` for `list`, I am not a fan of this kind of special casing, the user can reset the threshold themselves if they want. Or it needs to be done for `disasm` and `weblist` as well.

A bit aside, the `linesnoinlines` name does not read too well. Maybe we should consider making `noinlines` a separate flag which can be combined with any granularity. By default it would be false, the `addressnoinlines` and `inlines` granularities would implicitly act as if it's true and it can be explicitly set to `true` as well.

Also, apart from having the consistent behavior a good idea anyway, I am curious whether the desire to see the allocated bytes attributed to `bytes.NewBuffer` has to do with inlining. Depending on what the compiler was able to inline for how the allocation stacks should be visualized seems a bit strange.

**Comment by ardan-bkennedy** [comment]
As someone who teaches and uses these profiles. It is frustrating when the allocation is flat and the tool doesn't show that. To me the tool is not accurate. It should take into account the complier optimizations that were applied. This is truely a flat allocation that is escaping because of the calls to io.ReadFull. I have had this conversation with others on the team in the past. Prior to 1.8 (I don't rememeber of the top of my head when this changed), this used to show as flat.

**Comment by rauls5382** [comment]
There is a reason for this difference. What is lost on this issue report is that weblist is an assembly-level listing, while list is a source-level listing. As such, for weblist we need to generate a report with address-level granularity, and we disable inlines to match the addresses back into the noinline frame. Perhaps we should have used "addresses", but then the code to match the samples back to the source would have been (slightly?) more complicated. 

For list we generate a report with line level granularity, which honors inline frames. We honor inline frames if present by default, for this and any other profile type, in order to represent the program as close as possible to its source. Arguably the list output is the correct one, as the allocation is done in bytes.NewBuffer, not in algOne.

If there is a strong desire for this kind of output, I agree we could add a "linesnoinlines" format and allow list in combination with linesnoinlines (although I argue that lines should still be the default). Separating "noinlines" into its own flag sounds like a good idea to me.

As for previous behavior being similar to "linesnoinlines", this is likely due to changes in the golang runtime which started producing inline frames via online symbolization.

Finally, the reason for nodecount=0 for list is just to ensure we generate all the functions that match the regexp. For the other options we use trim=false, which also overrides it. Without looking too closely, perhaps we should replace the nodecount=0 by trim=false, for consistency.

**Comment by ardan-bkennedy** [comment]
"Arguably the list output is the correct one, as the allocation is done in bytes.NewBuffer, not in algOne."

This is so confusing to me and I have been told the same thing in the past. How is this correct when this is not what really happened? The escape analysis report will specifically state the allocation comes from an interface-conversion on the call to io.ReadFull. I rather the profile output match the escape analysis report every time. This leads to consistency in reporting allocations with what, where and why they are happening. Profiler is supposed to be telling me what happened, not what would have happened if the compiler didn't optimize.

**Comment by rauls5382** [comment]
It is correct in the context of the source. If you look at the source, we have algOne calling bytes.NewBuffer and bytes.NewBuffer did the allocation.

Of course you're correct that the compiler did inline and that the actual allocation ended up happening from algOne. It is a bit of a philosophical question as to whether we should represent the program as it was written or as the code that was executed. pprof attempts to model the former, at least when it comes to inline functions, as it is useful for somebody trying to analyze and optimize their application by changing the source.

I agree the latter is also beneficial, and we have that noinlines option, which I agree could be made more general.

Keep in mind that we want pprof to have the same behavior regardless of whether we're looking at a cpu or heap profile (or any other).

**Comment by hyangah** [comment]
I also think the list output seems more reasonable for most users - that helps users (who are not familiar with compiler optimization details and possibility of inlining) to navigate the source of NewBuffer and understand the nature of the NewBuffer implementation. What weblist currently presents seems more suitable for advanced use cases (like inspecting escape analysis reports) and I wish the default for weblist could be changed :-(

I didn't know the weblist and the list commands run in different granularity mode until now. `pprof -h` doesn't surface this detail. I wish they have the 
<pre>
 -list            Output annotated source for functions matching regexp
  ...
 -weblist         Display annotated source in a web browser
</pre>

Having noinlines as a separate flag seems like a good idea. The granularity option is already too complicated.

While we are at it, I want to mention the documentations about granularity needs improvement as well. Comments on addresses, and noinlines options seem like a documentation error.
<pre>
  Option groups (only set one per group):
    ...
    granularity      
      -addresses       Aggregate at the function level.
      -addressnoinlines Aggregate at the function level, including functions' addresses in the output.
      -files           Aggregate at the file level.
      -functions       Aggregate at the function level.
      -lines           Aggregate at the source code line level.
      -noinlines       Aggregate at the function level.
</pre>

**Comment by ardan-bkennedy** [comment]
Is there a way to specify the granuarily on the `list` call? I can't figure out how to set this. This would solve my problems if I could choose the granularity I wanted.

**Comment by nolanmar511** [comment]
Right now, the granularity can't be changed for output formats which have the granularity overridden by `applyCommandOverrides`

@aalexand, @rauls5382  -- is that something we should try to change? It seems useful to me, but could create com pitfalls (like `disasm` really probably does need addresss information)

**Comment by aalexand** [comment]
@nolanmar511 @rauls5382 @hyangah @ardan-bkennedy I sent #420 for review which will support specifying granularity like `-list foo -noinlines` which is what I think we discussed here, please take a look.

**Comment by aalexand** [comment]
@ardan-bkennedy I think #420 should address the original report by allowing using "-noinlines" with "-list" reports.
