### ISSUE TITLE
Filter nodes with headers in range x:y

### ISSUE THREAD

**Issue by svar29** [google/pprof#417]
I would like to have an option to filter the text output by things like cum,cum%,flat,flat%,sum%.
I am running this and only want output which has cum% greater than 50%.
```
(pprof) top
Showing nodes accounting for 30683.10kB, 100% of 30683.10kB total
Showing top 10 nodes out of 48
      flat  flat%   sum%        cum   cum%
23965.32kB 78.11% 78.11% 23965.32kB 78.11%  xxx
 2084.21kB  6.79% 84.90%  2084.21kB  6.79%  yyy
 1536.56kB  5.01% 89.91%  1536.56kB  5.01%  zzz
  532.26kB  1.73% 91.64%   532.26kB  1.73%  aaa
     514kB  1.68% 93.32%      514kB  1.68%  bbb
     514kB  1.68% 94.99%      514kB  1.68%  ccc
  512.50kB  1.67% 96.66%   512.50kB  1.67%  ddd
  512.17kB  1.67% 98.33%   512.17kB  1.67%  eee
  512.07kB  1.67%   100%   512.07kB  1.67%  fff
         0     0%   100%      514kB  1.68%  ggg
```
I already explored nodefraction, edgefraction and tagfocus but couldnt find a way.

**Comment by nolanmar511** [comment]
Pprof currently doesn't support.

For my understanding, what's the utility of this for you over using `-cum` to sort to sort by the cumulative percentages?

**Comment by aalexand** [comment]
Yes, it seems using `-cum` and just look at the first N rows until the cum value is lower than the desired threshold should work in this case.

**Comment by svar29** [comment]
@aalexand @nolanmar511 I want to setup an alert on diff of two profiles if any of the cum% value exceeds certain threshold. I didnt want to go into text parsing to achieve that so was wondering if there is a better way to achieve that. Maybe just a machine readable format of above output?
