### ISSUE TITLE
UI filters don't seem to apply to flame graph view.

### ISSUE THREAD

**Issue by nolanmar511** [google/pprof#431]
Playing with the pprof web UI, I found that I could apply filters in (for example) the graph view, and those filters would also be applied to all views, excluding the flame graph. I also wasn't apply to add filters when I was in the flame graph view.

**Comment by aalexand** [comment]
@nolanmar511 Could you list the steps to repro?

**Comment by nolanmar511** [comment]
This is what I did:

1. Run `pprof -http=: /path/to/profile`
2. Go to graph view, click a node, then do "Refine > show". Only that node appear in the graph view.
3. Switch to the `Top` view, and still only that node appears (so filters seem to stick when switching views).
4. Switch to the 'Flame` view, and the complete flame graph is visible. 
5. Click on a node in flame graph, and then try to "Refine" -- I wasn't about to click Focus, Ignore, Hide or Show.
