### ISSUE TITLE
pprof does not symbolize all functions inside a binary

### ISSUE THREAD

**Issue by romange** [google/pprof#443]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?
latest - fe60075897a924c5b39be9120b21330369701bc0

If you are using pprof via `go tool pprof`, what's your `go env` output?
If you run pprof from GitHub, what's the Git revision?
fe60075897a924c5b39be9120b21330369701bc0

### What operating system and processor architecture are you using?
Linux 4.15.0-36-generic, Ubuntu 18, 

### What did you do?
Generated .prof file using gperftools.  Attached via [my drive](https://drive.google.com/file/d/1BllzPN4wckvnrpyY0hQJ0MfcSqjamcr0/view?usp=sharing). 
Then run ` ./bin/pprof  geo_service_18_11_27_12_46_15_25_27112018_153219.prof`  
Got the following message 
```
Some binary filenames not available. Symbolization may be incomplete.
Try setting PPROF_BINARY_PATH to the search path for local binaries.
```
And one of the entries in top40 was 
`0.01s  0.23% 82.86%      1.25s 29.34%  [geo_service_18_11_27_12_46_15_25] (inline)`

### What did you expect to see?
All the entries in top40 accounted for and symbolized.

### What did you see instead?
An "anchor" for, probably, multiple symbols that represents an unknown function. 
I tried to debug symbolizer.go and saw that `newMapping` function gets the following mapping:
`&{5 0 18446744073709551615 0   false false false false 0 0}`
It seems that its field `File` is not defined.

**Comment by nolanmar511** [comment]
@romange -- could you add the complete output from `pprof -top` that you get with this profile. I think my output is different from yours, since I think I'm missing binaries which are used to get symbol information for your profile. 

This is my output:
```
Local symbolization failed for geo_service_18_11_27_12_46_15_25: stat /ubimo/bin/geo_service_18_11_27_12_46_15_25: no such file or directory
Local symbolization failed for libpthread-2.27.so: stat /lib/x86_64-linux-gnu/libpthread-2.27.so: no such file or directory
Local symbolization failed for libm-2.27.so: stat /lib/x86_64-linux-gnu/libm-2.27.so: no such file or directory
Local symbolization failed for libc-2.27.so: stat /lib/x86_64-linux-gnu/libc-2.27.so: no such file or directory
Local symbolization failed for libprotobuf.so.10.0.0: stat /usr/lib/libprotobuf.so.10.0.0: no such file or directory
Local symbolization failed for libtcmalloc_and_profiler.so.4.5.3: stat /usr/lib/libtcmalloc_and_profiler.so.4.5.3: no such file or directory
Local symbolization failed for libcityhash.so.0.0.0: stat /usr/lib/libcityhash.so.0.0.0: no such file or directory
Some binary filenames not available. Symbolization may be incomplete.
Try setting PPROF_BINARY_PATH to the search path for local binaries.
File: geo_service_18_11_27_12_46_15_25
Type: cpu
Showing nodes accounting for 4.15s, 97.42% of 4.26s total
Dropped 9 nodes (cum <= 0.02s)
      flat  flat%   sum%        cum   cum%
     2.58s 60.56% 60.56%      2.82s 66.20%  [geo_service_18_11_27_12_46_15_25]
     0.87s 20.42% 80.99%      3.59s 84.27%  [libpthread-2.27.so]
     0.49s 11.50% 92.49%      0.51s 11.97%  [libc-2.27.so]
     0.11s  2.58% 95.07%      0.16s  3.76%  [libprotobuf.so.10.0.0]
     0.07s  1.64% 96.71%      0.07s  1.64%  [libtcmalloc_and_profiler.so.4.5.3]
     0.03s   0.7% 97.42%      0.03s   0.7%  [libm-2.27.so]
         0     0% 97.42%      0.23s  5.40%  <unknown>
         0     0% 97.42%      0.07s  1.64%  evbuffer_add_buffer
```

Also, it might be useful if you upload the profile produced by `pprof -proto /path/to/profile`, since this version of the profile should have all the symbol information which pprof does have.

It seems likely that your binaries might not have all the symbols needed (cc/@aalexand and @lannadorai, since they would both know more about gperftool profiles than me). Or, given that an inlined function is missing information, there could be something happening that's specific to inlined functions.

**Comment by aalexand** [comment]
@romange Can you try passing the binary path as the first argument? Such as `pprof -top ./bin/pprof geo_service_18_11_27_12_46_15_25_27112018_153219.prof /path/to/profile`.

**Comment by romange** [comment]
I've run `PPROF_BINARY_PATH=${MY_BIN_LIB_PATH}  ./bin/pprof -proto  ${path_to_bin} my_gperftools_prof.prof`
It created `profile001.pb.gz` which I uploaded it [here](https://drive.google.com/file/d/1Ls1nW7yoeuFMs4bkm7LHCyWtypcs_DIE/view?usp=sharing)

I can run pprof on it and view top40 which contains the invalid entry `0.01s  0.23% 82.86%      1.25s 29.34%  [geo_service_18_11_27_12_46_15_25] (inline)`

The entry itself takes is not important. the problem with it is that I think it screws the call-graph and somehow accounts for 30%  of total  CPU time. So the svg graph, for example, puts it in the center as big  fat hotspot.

**Comment by infa-mkaranth** [comment]
@aalexand , I also faced the same problem. I am trying it from Windows machine where I copied the prof, envoy binary and linux folder from remote server. Function names are shown as Unknown...please help me to resolve this.

**Comment by haoruolei** [comment]
hi @infa-mkaranth I faced the similar issue, did you ever get to resolve it? Thanks
