### ISSUE TITLE
Source for internal/binutils/testdata/exe_linux_64

### ISSUE THREAD

**Issue by ssgelm** [google/pprof#451]
As far as I can tell, the source file for `internal/binutils/testdata/exe_linux_64` is not included.  This is a problem for packaging this in Debian where they do not allow pre-built binaries of any kind.  It seems to just be a simple "hello world" application but it would make it way easier to package if there was a script to build this file (like there seems to be for mac).  It would also be helpful to have a script to automate building the malformed binaries in the same directory but I'm less worried about those because they're not working binaries anyway.

**Comment by ssgelm** [comment]
Makes sense.  Thanks so much for the help!

**Comment by kalyanac** [comment]
Fixed with #452
