### ISSUE TITLE
HTTP mode needs a !browser option

### ISSUE THREAD

**Issue by ahh** [google/pprof#458]
### What version of pprof are you using?

As downloaded via `go get -u github.com/google/pprof` today. Not sure how to get a better version ID. Go version 1.10.2.

### What operating system and processor architecture are you using?

Linux x86-64.

### What did you do?

I frequently run pprof on a remote machine via SSH. The HTTP interface--which is great, btw, I really wish I'd had this years ago!--launches a browser on that remote machine.  This is not useful for me (I do in fact run Xforwarding, but the remote browser isn't particularly good.) I'd much rather use my local workstation's browswer to visit <remote:port>, which does in fact work.  But I'd like to skip launching the browser.

Via source digging, I worked out that [it checks if stdout is interactive](https://github.com/google/pprof/blob/e84dfd68c163c45ea47aa24b3dc7eaa93f6675b1/pprof.go#L101) and thus the very silly-looking "pprof -http : <profile> > /dev/null" works but this is, well, silly, and hardly discoverable. This wants a flag or similar way to say "no thanks, skip the browser please."

Related, but ironic: if you don't open a browser, there's no command-line output of the path we're serving on. Since by default (with -http : or similar) the port is randomly chosen, we can't know it. So even with a  >/dev/null or | tee hack, I have to write out "-http :12345" or something like that so I can know where to look. So I feel pretty strongly we should log something like: 

"Serving UI on http://localhost:19553"

(I don't care at all about the format so long as there's a pastable URL in there.)

Thanks!

**Comment by kalyanac** [comment]
Thank you for your suggestion. I will leave this open till we get a chance to implement it. 

We will welcome a PR if you get to it sooner.

**Comment by ahh** [comment]
And here I was thinking that quitting Google meant I'd never have to write go again! :)

https://github.com/google/pprof/pull/462
