### ISSUE TITLE
build is failing due to gosimple

### ISSUE THREAD

**Issue by jeffallen** [google/pprof#465]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

tip

### What did you do?

Looked at Travis.

### What did you expect to see?

Working build.

### What did you see instead?

```
0.02s$ gosimple ./...
Gosimple has been deprecated. Please use staticcheck instead.
unsupported version of go: exit status 2: flag provided but not defined: -compiled
usage: list [-e] [-f format] [-json] [build flags] [packages]
Run 'go help list' for details.
The command "gosimple ./..." exited with 1.
```

**Comment by aalexand** [comment]
I am not sure what this is about - at least now I don't think any automation or script in this repo use gosimple. Closing - but please re-open with clarifications if this is still failing for you.

**Comment by nolanmar511** [comment]
Looks like this if it was fixed with https://github.com/google/pprof/pull/466
