### ISSUE TITLE
Support passing a directory (containing many pprof files) 

### ISSUE THREAD

**Issue by jcorbin** [google/pprof#480]
I'd like to add support to ease merging many pprof files, without needing to pass them all as explicit arguments; in short, I'd like to be able to run `pprof -proto some/path/to/foo/ some/path/to/foo.pprof` to merge all of the files under some directory, into a sibling file alongside the directory.

Options that I can see from an initial code read:

### Modify the default `internal/driver.fetch()` func

- Either with "is a directory" fault-fixing logic (e.g. under the file open branch)
- or with a "if the arg ends in a trailing slash", then treat it as a directory.

However we get into directory mode, fetch would then use `"github.com/google/pprof/profile".Merge` to merge them all. Intentionally leaving off any measurement matching works for my use case, since that should all be identical anyhow, and I'm really not interested in re-sampling affects on my data.

### Instead do it at source expansion time in `internal/driver.fetchProfiles`

With some sort of "is the source a local path (ending in a /)?" logic.

Not sure if this breaks semantics with existing `Fetcher`s out there...

### Speaking of `Fetcher`

Maybe I should just wrap the pprof driver package itself, and inject my own `Fetcher` that would use `profile.Merge` as described above.

However this seemed like a natural enough extension of the upstream pprof tool.

**Comment by aalexand** [comment]
Doesn't `pprof -proto -output=/tmp/out.pb.gz /some/input/dir/*` do that?

**Comment by aalexand** [comment]
In other words, pprof already supports multiple files as input and there are multiple ways to express that input without having to list the files explicitly on the command line - shell globs, `find` etc. Making the utility of those tools a part of pprof seems overkill.

**Comment by jcorbin** [comment]
Yes that works, but:
- only if you have few enough files that you don't blow out an your os's exec args buffer
- sometimes you're running pprof itself over many directories, e.g. itself under xargs; in that case, you have to wrap pprof in a bash to get the glob expansion, e.g. like `xargs -I BASE bash -c 'pprof -proto BASE/* -output BASE.pprof'`

At any rate, I can understand your viewpoint, and believe I can meet some of my needs by breaking the glass, and integrating the pprof driver package into my own go program that injects a `driver.Fetcher` capable of loading entire directories.

**Comment by harveylihr** [comment]
When I pass multiple perf.data files to pprof, some files are recognized as either empty input file or wrong format. While when I use pprof with the specific "wrong" input file, it works.

**Comment by kalyanac** [comment]
@harveylihr, That seems unrelated to this issue. Can you please open a new issue for discussing it?

**Comment by harveylihr** [comment]
> @harveylihr, That seems unrelated to this issue. Can you please open a new issue for discussing it?

Sure. Thanks!
