### ISSUE TITLE
Exclude certain functions from aggregation?

### ISSUE THREAD

**Issue by tudor** [google/pprof#485]
I'm using gperftools to generate CPU profiles for C++ binaries, and the (Go) pprof for analyzing them (usually by converting them to PDF).

pprof is great when the execution flow is determined by the instruction pointer, but visualization isn't great when you use some form of dynamic dispatch; the "dispatch" function is aggregated, and so completely different code paths (A -> dispatch() -> B and C -> dispatch() -> D) are merged ( (A, B) -> dispatch() -> (C, D) ).

In my concrete example, the code uses a lot of callbacks called via `std::function` objects. Unfortunately, all calls to `std::function<T>::operator()` (well, `std::_Function_handler::_M_invoke`) are aggregated and show up as the same node in the output, even though the call stacks both *above* and *below* are different.

But aggregating in `std::function` is meaningless. I want to identify which caller of `std::function` corresponds to which downstream stack, and this distinction is now lost because these different call stacks are joined in the middle.

I'd like to completely exclude `std::_Function_handler::_M_invoke` (and other such dynamic dispatch functions) from aggregation.

**Comment by aalexand** [comment]
Try `-hide` filter?

**Comment by nolanmar511** [comment]
I'm assuming you're using a graph output format (like -web or -gv). If that is the case, it might be helpful to add the `-call_tree` flag. 

There's also the flame graph in the interactive web interface (viewable using the command `pprof -http=: /path/to/profile`, then selecting the "Flame Graph" view) -- which, like the call tree, separates nodes out by caller. It's also just, generally, my favorite of `pprof`'s view for initially looking at a profile.

**Comment by aalexand** [comment]
@tudor I think one of the suggestions here addresses your question. Please re-open the issue if not.
