### ISSUE TITLE
pprof  --text no result

### ISSUE THREAD

**Issue by dongming** [google/pprof#489]
version:
gperftools-2.5 
libunwind-0.99
analysis java mem probem, i can get the dump file like this:
-rw------- 1 root root      44550 Oct 15 12:36 dump_30713.0065.heap
-rw------- 1 root root      44491 Oct 15 12:37 dump_30713.0066.heap
-rw------- 1 root root      44491 Oct 15 12:38 dump_30713.0067.heap
-rw------- 1 root root      44491 Oct 15 12:39 dump_30713.0068.heap
-rw------- 1 root root      44550 Oct 15 12:40 dump_30713.0069.heap
-rw------- 1 root root      44550 Oct 15 12:41 dump_30713.0070.heap
-rw------- 1 root root      44550 Oct 15 12:42 dump_30713.0071.heap
-rw------- 1 root root      44550 Oct 15 12:43 dump_30713.0072.heap
-rw------- 1 root root      44550 Oct 15 12:44 dump_30713.0073.heap

content of one:
heap profile: 274808: 270549613 [71263064: 77431032638] @ heapprofile
274808: 270549613 [71263064: 77431032638] @

MAPPED_LIBRARIES:
00400000-00401000 r-xp 00000000 00:00 469945      /root/jdk/bin/java
00600000-00601000 rw-p 00000000 00:00 469945      /root/jdk/bin/java
00df0000-350e0000 rw-p 00000000 00:00 0           [heap]
c0000000-1007a0000 rw-p 00000000 00:00 0
1007a0000-140000000 ---p 00000000 00:00 0
7f1c73cc4000-7f1c73cc5000 ---p 00000000 00:00 0
7f1c73cc5000-7f1c744c5000 rw-p 00000000 00:00 0
7f1c74cc6000-7f1c74cc7000 ---p 00000000 00:00 0
7f1c74cc7000-7f1c754c7000 rw-p 00000000 00:00 0
7f1c754c7000-7f1c754c8000 ---p 00000000 00:00 0
7f1c754c8000-7f1c75cc8000 rw-p 00000000 00:00 0
7f1c75cc8000-7f1c75cc9000 ---p 00000000 00:00 0
7f1c75cc9000-7f1c764c9000 rw-p 00000000 00:00 0
7f1c7a4d1000-7f1c7a4f1000 rw-p 00000000 00:00 0
7f1c7bb18000-7f1c7bbd8000 rw-p 00000000 00:00 0
7f1c7bbd8000-7f1c7bbdb000 ---p 00000000 00:00 0
7f1c7bbdb000-7f1c7c0b9000 rw-p 00000000 00:00 0           [stack:2971]
7f1c7c0b9000-7f1c7c1f9000 ---p 00000000 00:00 0
7f1c7c1f9000-7f1c7c799000 rw-p 00000000 00:00 0
7f1c7c799000-7f1c7c79c000 ---p 00000000 00:00 0
7f1c7c79c000-7f1c7c89a000 rw-p 00000000 00:00 0           [stack:32649]
7f1c7c89a000-7f1c7c8b6000 r--- 00393000 00:00 471563      /root/jdk/jre/lib/ext/cldrdata.jar
7f1c7c8b6000-7f1c7c8b9000 ---p 00000000 00:00 0
7f1c7c8b9000-7f1c7c9b7000 rw-p 00000000 00:00 0           [stack:8378]
7f1c7c9b7000-7f1c7c9ba000 ---p 00000000 00:00 0
7f1c7c9ba000-7f1c7cab8000 rw-p 00000000 00:00 0           [stack:32647]
....
when i use commad :
pprof  --text $JAVA_HOME/bin/java dump_30713.0004.heap

nothing but:
Using local file /root/jdk/bin/java.
Using local file dump_30713.0004.heap.

anyone give some help? 
thx

**Comment by aalexand** [comment]
@dongming Can you include full data to reproduce?

**Comment by dongming** [comment]
@aalexand i use  gperftools  and set env TCMALLOC_STACKTRACE_METHOD=x86(or the java process will crash)
so the dump file format is different, i think it is not a probem of pprof
thx

**Comment by aalexand** [comment]
The line

```
274808: 270549613 [71263064: 77431032638] @
```

suggests that there is no stack recorded here. I don't think this is a pprof issue, it should probably be reported to gperftools.
