### ISSUE TITLE
With multiple input perf.data files, some files are recognized as either empty input files or unrecognized profile format

### ISSUE THREAD

**Issue by harveylihr** [google/pprof#500]
When I run pprof with multiple perf.data files (e.g. pprof -top *.data), some files will be randomly recognized as empty input files or in unrecognized profile format. 
However, when I run pprof with those "wrong" files, it can successfully generate report. 

[pprof.log](https://github.com/google/pprof/files/3866898/pprof.log)

**Comment by nolanmar511** [comment]
Does this happen fairly consistently?
Can you provide more details on how to reproduce this?

**Comment by harveylihr** [comment]
> Can you provide more details on how to reproduce this?

Please find 10 raw perf.data in the attached file, when using pprof to convert & view them (e.g. pprof -top *.data), some perf.data files cannot be recognized. 
[test_perfdata.zip](https://github.com/google/pprof/files/3870393/test_perfdata.zip)
