### ISSUE TITLE
How can I located the function in pprof  with method has "*" ?

### ISSUE THREAD

**Issue by yaoyuan20181** [google/pprof#512]
(pprof) list encoding/json.(*encodeState).marshal   
parsing argument regexp encoding/json.(*encodeState).marshal: error parsing regexp: missing argument to repetition operator: `*`
(pprof) list encoding/json.(\*encodeState).marshal 
Total: 15.91s

**Comment by aalexand** [comment]
By escaping the special characters in this regular expression:

```
(pprof) list encoding/json.(\*encodeState).marshal
(pprof) list encoding/json.([*]encodeState).marshal
```

**Comment by lucky-tony09** [comment]
(pprof) list artical/go/pprof/work.([*]Worker).Show
Total: 39.27s
sorry，your method is still ineffective

**Comment by guoxuncn** [comment]
list marshal

**Comment by huanggze** [comment]
any help?
