### ISSUE TITLE
Hiding/Ignoring a frame does not update the calculations throughout the rest of the profile.

### ISSUE THREAD

**Issue by NHDaly** [google/pprof#516]
It would be really nice if ignoring/hiding a function in the pprof UI would update the calculations throughout the Profile, recalculating the percentages and UI displays.

----------------------

Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

f9b734f9ee64d0f5b63636a45cc77ed2744997ab

### What operating system and processor architecture are you using?

MacOS / x86

### What did you do?

Viewing a profile that has its time dominated by a single function. We want to filter out that function, and have the UI re-calculate all the sample percentages throughout the profile.

For example, in this profile (which we generated from a Julia program, via https://github.com/vchuravy/PProf.jl, via `@pprof peakflops()`), the time is dominated by idle threads (`__psynch_cvwait`), which we would like to filter out.
[profile.pb.gz](https://github.com/google/pprof/files/4366401/profile.pb.gz)

<img width="616" alt="Screen Shot 2020-03-22 at 5 39 03 PM" src="https://user-images.githubusercontent.com/1582097/77261317-0c78e380-6c64-11ea-9e28-ff7d04b803cd.png">

But if you filter it out via `-ignore` or `-hide`, it doesn't change the relative percentages in any of the rest of the profile, so the boxes and arrows are all still small.
<img width="555" alt="Screen Shot 2020-03-22 at 5 37 54 PM" src="https://user-images.githubusercontent.com/1582097/77261293-e2272600-6c63-11ea-88b9-864bf0a9a48e.png">

### What did you expect to see?

I expected to see the percentages adjust throughout the profile UI.

### What did you see instead?

The profile remains unchanged except for the filtered-out nodes.

**Comment by aalexand** [comment]
Please try `-ignore=__psynch_cvwait -relative_percentages`. Please re-open if it doesn't do what you want.

**Comment by aalexand** [comment]
Alternatively you can first save a profile with filtered out stacks, then view it.

```
pprof -proto -output=/tmp/output.pb.gz -ignore=__psynch_cvwait input.pb.gz
pprof ... /tmp/output.pb.gz
```

**Comment by NHDaly** [comment]
Sorry i didn't respond for a long time.

Thank you! Yes, this helped tremendously! :) We were specifically hoping to see the percentages adjust dynamically in the web UI, and i can confirm that passing `-relative_percentages` to the `-http` call does indeed cause `ignore` to recompute the percentages. Thank you! :)

E.g. with this invocation, ignoring patterns through the web interface does indeed recompute the percentages. Thanks :)
```
$ pprof -relative_percentages -http localhost:52522 profile.pb.gz
```
