### ISSUE TITLE
[feature] alias 'q' to 'quit'

### ISSUE THREAD

**Issue by prattmic** [google/pprof#524]
Almost every single pprof session I run ends in:

```
(pprof) q
unrecognized command: "q"
(pprof) ^D
```

I likely have a habit because the pprof shell looks a lot like gdb, which does support q to quit.

Would there be an objection to making 'q' as alias for 'quit'? If not, I can send a PR.

**Comment by aalexand** [comment]
Sounds good to me to add this alias.
