### ISSUE TITLE
internal/driver fails at Go tip due to changes in pprof

### ISSUE THREAD

**Issue by andybons** [google/pprof#526]
See https://travis-ci.org/github/google/pprof/jobs/678277764 for an example failure.

This is due to https://go.googlesource.com/go/+/2ff1e3e, specifically the behavior change mentioned in the commit message:

> Providing the "seconds" parameter to other types of profiles is an error.

@hyangah

**Comment by hyangah** [comment]
Why is the test querying the "/debug/pprof/goroutine" endpoint with "seconds" parameter?
Can the test be fixed?

**Comment by hyangah** [comment]
Actually, I am thinking to fix from go to expand the list of endpoints that support "seconds" param.

**Comment by nolanmar511** [comment]
I think this test could also be changed, if that's the action we should take. 

@wyk9787 -- Could you take a look?

**Comment by wyk9787** [comment]
> I think this test could also be changed, if that's the action we should take.
> 
> @wyk9787 -- Could you take a look?

Will do.

**Comment by andybons** [comment]
Thanks for the quick responses, everyone.

**Comment by hyangah** [comment]
FYI - https://go-review.googlesource.com/c/go/+/229537 is merged. Not sure if the current test will pass though because the 'seconds' parameter is now not ignored.
