### ISSUE TITLE
Go 1.14 cmdline & trace profiles parse error on arm/arm64

### ISSUE THREAD

**Issue by povilasv** [google/pprof#529]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

trying https://github.com/google/pprof/commit/8f1c0db96fd2793f0e7f2c1b22ef34c16a904583 master version

### What operating system and processor architecture are you using?

Go 1.14 binary exposes metrics on arm64 arhitecture running in a container.

HOST OS: Linux rock64-0 5.6.3-1-ARCH #1 SMP Sun Apr 12 15:53:26 UTC 2020 aarch64 GNU/Linux
Container: Alpine:3.9 -> https://github.com/conprof/conprof/blob/master/Dockerfile

### What did you do?

```
kubectl port-forward conprof-0 8080

wget http://localhost:8080/debug/pprof/trace
-2020-04-28 18:16:06--  http://localhost:8080/debug/pprof/trace
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘trace’

trace                                 [ <=>                                                          ]   5.00K  --.-KB/s    in 0s      

2020-04-28 18:16:08 (97.5 MB/s) - ‘trace’ saved [5115]

wget http://localhost:8080/debug/pprof/cmdline
--2020-04-28 18:16:41--  http://localhost:8080/debug/pprof/cmdline
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 103 [text/plain]
Saving to: ‘cmdline’

cmdline                           100%[=============================================================>]     103  --.-KB/s    in 0s      

2020-04-28 18:16:41 (6.38 MB/s) - ‘cmdline’ saved [103/103]
```

I've added `.txt` suffix so that I can upload to github
[trace.txt](https://github.com/google/pprof/files/4546765/trace.txt)
[cmdline.txt](https://github.com/google/pprof/files/4546767/cmdline.txt)

### What did you expect to see?

pprof to work

### What did you see instead?

Then trying to pprof those profiles:
```
pprof trace 
trace: parsing profile: unrecognized profile format
pprof: failed to fetch any source profiles

pprof cmdline
cmdline: parsing profile: unrecognized profile format
pprof: failed to fetch any source profiles
```

Ref https://github.com/conprof/conprof/issues/46

**Comment by nolanmar511** [comment]
It looks like there is a tool to convert traces to a format that can be opened by the pprof CLI. It is documented here: https://golang.org/cmd/trace/

The `pprof` CLI only supports opening profile.proto files (defined [here](https://github.com/google/pprof/blob/master/proto/profile.proto)), perf.data files (details [here](https://github.com/google/pprof/blob/master/proto/profile.proto)), and a limited number of legacy profiles. So, it does not support opening traces directly.

**Comment by nolanmar511** [comment]
@hyangah -- Do you know if it would be possible to have the docs for `net/http/pprof` updated to mention `go tool trace` (or who to reach out to about this)? I wonder if this might be a common confusion going forward.

**Comment by hyangah** [comment]
https://go-review.googlesource.com/c/go/+/230538

**Comment by povilasv** [comment]
Thank you for the information and sorry for the bother!
