### ISSUE TITLE
The master branch is Incompatible with go version < 1.13

### ISSUE THREAD

**Issue by xuyixin1996** [google/pprof#538]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

master branch

### What operating system and processor architecture are you using?

golang 1.12

### What did you do?

To reproduce this issue:
```
docker run -i -t --rm golang:1.12.7 go get -u github.com/google/pprof
# github.com/google/pprof/internal/driver
src/github.com/google/pprof/internal/driver/settings.go:27:14: undefined: os.UserConfigDir
[DEBUG] container new status:  removing
Exit by user interrupt.
```

this is caused by [UserConfigDir](https://golang.org/src/os/file.go?s=13013:13049#L416) only support golang > 1.13

### What did you expect to see?
Okay not sure if this is on purpose, actually some of our automation tool break due to this Incompatible change

**Comment by kalyanac** [comment]
pprof follows the [Go support policy](https://golang.org/doc/devel/release.html#policy): "Each major Go release is supported until there are two newer major releases."

So, 1.13 is the lowest supported version at this time.

**Comment by xuyixin1996** [comment]
got it, thanks!
