### ISSUE TITLE
Can't install tool

### ISSUE THREAD

**Issue by 3xlerman** [google/pprof#550]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

If you are using pprof via `go tool pprof`, what's your `go env` output?
If you run pprof from GitHub, what's the Git revision?

### What operating system and processor architecture are you using?
Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz

### What did you do?
Can't install tool, getting this error:

go/src/github.com/google/pprof/internal/driver/settings.go:27:17: error: reference to undefined identifier ‘os.UserConfigDir’
  dir, err := os.UserConfigDir()
                 ^
go env:

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lerman/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lerman/go"
GORACE=""
GOROOT="/usr"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-linux-gnu/8"
GCCGO="/usr/bin/x86_64-linux-gnu-gccgo-8"
CC="x86_64-linux-gnu-gcc-8"
CXX="x86_64-linux-gnu-g++-8"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build397245762=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

**Comment by aalexand** [comment]
See #538
