### ISSUE TITLE
Non-text files are incorrectly treated as text files when auto-converting line endings

### ISSUE THREAD

**Issue by weiwei-lin** [google/pprof#551]
### What version of pprof are you using?
6609db78bf680fce22b263370f901afd68abc791

### What operating system and processor architecture are you using?
Linux x86_64

### What did you do?
Checkout the repo.
`git clone git@github.com:google/pprof.git`

### What did you expect to see?
A repo with no uncommitted changes.

### What did you see instead?
```
git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   doc/images/callgraph.png
        modified:   internal/binutils/testdata/exe_mac_64
        modified:   internal/binutils/testdata/lib_mac_64
        modified:   internal/report/testdata/sample.bin
```

### Proposed Fix
change `* text eol=lf` to `* text=auto eol=lf` in .gitattributes

**Comment by aalexand** [comment]
@wyk9787 Could you take a look at it?

**Comment by wyk9787** [comment]
Thanks for catching this! 

I thought I definitely added `auto` when I was experimenting but somehow it got taken away.

**Comment by weiwei-lin** [comment]
Thanks for fixing this.
