### ISSUE TITLE
Add support for llvm-addr2line.

### ISSUE THREAD

**Issue by wyk9787** [google/pprof#553]

**Comment by sfc-gh-sgiesecke** [comment]
Could this be considered fixed by #598? It adds support for llvm-symbolizer, which llvm-addr2line is basically an alias of.

**Comment by aalexand** [comment]
#598 did not add support for llvm-symbolizer, it existed before.

**Comment by aalexand** [comment]
@wyk9787 Do you remember why this issue was filed and why the existing llvm-symbolizer support was not considered sufficient?

**Comment by wyk9787** [comment]
It was filed during the code review: https://github.com/google/pprof/pull/545#discussion_r450405281.

**Comment by aalexand** [comment]
Thanks. Thinking of it now, I don't think it's very likely that llvm-addr2line is present but llvm-symbolizer is missing. So I think this is moot / not very important.
