### ISSUE TITLE
c++filt crash when using pprof to see the hprof file generated by gperftools

### ISSUE THREAD

**Issue by jaycelq** [google/pprof#555]
I use gperftools to generate the hprof file, and use pprof to see the result, but the c++filt always crash, and can not use it. Is it relevant to my compiler? I use gcc 9.1.0 to compile my program.

![image](https://user-images.githubusercontent.com/4169335/87856368-58f1d880-c951-11ea-9a72-117b347ca839.png)
![image](https://user-images.githubusercontent.com/4169335/87856516-517eff00-c952-11ea-9e4a-215961e38d49.png)

![image](https://user-images.githubusercontent.com/4169335/87856348-3b247380-c951-11ea-885f-0062a93b1693.png)

Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?
![image](https://user-images.githubusercontent.com/4169335/87856301-d49f5580-c950-11ea-93f9-a0d84ac91a86.png)

If you are using pprof via `go tool pprof`, what's your `go env` output?
If you run pprof from GitHub, what's the Git revision?

### What operating system and processor architecture are you using?
CentOS
Linux 192-168-11-18 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?

If possible, provide a recipe for reproducing the error.
Attaching a profile you are trying to analyze is good.

**Comment by aalexand** [comment]
This doesn't look like a pprof issue. I suspect this will also reproduce if you try to use `/usr/bin/nm -n <your binary>`. You might want to try to upgrade your binutils, search for similar binutils bugs in their bug tracker and report to them or get a fresh `llvm-nm` in your PATH (pprof [prefers](https://github.com/google/pprof/blob/1a94d8640e99342fa76ae6296aaa921d08ac451f/internal/binutils/binutils.go#L145) `llvm-nm` over `nm`).

**Comment by jaycelq** [comment]
I upgrade binutils and the issue get fixed.
