### ISSUE TITLE
Enable back "test-mac (1.14, macos-10.15, 11.7)", "test-mac (1.14, macos-10.15, 12.0)", "test-mac (1.13, macos-10.15, 12.0)", "test-mac (1.13, macos-10.15, 11.7)" presubmit checks

### ISSUE THREAD

**Issue by aalexand** [google/pprof#567]
These are currently disabled, but I don't remember why.

**Comment by wyk9787** [comment]
Those are added in https://github.com/google/pprof/pull/563. I have asked @kalyanac to enable them.

**Comment by kalyanac** [comment]
I disabled all 1.13 tests, added 1.15 tests and xcode v 11.7, 12.

**Comment by aalexand** [comment]
"Disabled" as in removed from the configuration? If some tests are running, they should be required. Any unchecked state for a particular test in the project settings should be temporary and be associated with a bug.

**Comment by wyk9787** [comment]
The actual tests themselves will be removed in https://github.com/google/pprof/pull/563.

**Comment by kalyanac** [comment]
disabled = remove "Required" status check in repo settings. #563 drops support for Go 1.13 and adds 1.15 and new XCode versions. Garrett's comment includes mention of #563 which explains why the changes were made.
