### ISSUE TITLE
Feature Request: Call back previous commands in interactive mode

### ISSUE THREAD

**Issue by whereswaldon** [google/pprof#57]
I believe that this repo is the code that powers `go tool pprof`. If I'm wrong on that count, disregard everything else I say.

I'm using `pprof` on macOS 10.12.1 with go 1.7.3. I'm constantly using it in interactive mode, and it would be really nice to be able to call back previous commands with the "up" arrow key. Instead, of course, it prints `^[[A`, which I assume means that this isn't supported?

I completely understand if this isn't worth the development team's time, but I thought I would suggest it.

**Comment by dgryski** [comment]
There are a number of pure-Go readline implementations that could be integrated to allow this.

**Comment by rauls5382** [comment]
This is the upstream repo for the pprof tool. The  one in the Go distribution is an old snapshot of this codebase. We plan to eventually refresh it to a more recent version, I believe in Go 1.9

@dgryski : Any pointers to specific readline implementations? Are there any in use in the Go distribution?

**Comment by rauls5382** [comment]
I have an initial prototype for this using github.com/chzyer/readline at
https://github.com/rauls5382/pprof/tree/readline

Would you like to try it out and see if it is useful? It lets you recall and edit commands from the current session, but it doesn't provide a persistent history across sessions. Would you find this useful, or is cross-session history the most useful part?

**Comment by whereswaldon** [comment]
@rauls5382 Thanks for trying to build it! The workflow that I usually want this feature for is calling back the last command to add some filters. While cross-session history might be useful, it wasn't my goal.

Sadly, I'm having some trouble running it. It compiles fine, but I can't open a profile with it. That said, I also can't open a profile with master. Has the profile format changed since the one shipping as `go tool pprof` with go 1.6.2? What do I need to do to record a memory profile in the format that this tool expects?

**Comment by rauls5382** [comment]
No, pprof should still be able to read profiles from older versions. On Go 1.8 now the handlers generate a native profile, but pprof will continue to read profiles from older versions.

If you can, attach a profile here and I can take a look. Did you collect it directly from the URL, or did you use pprof to fetch/save it?

**Comment by whereswaldon** [comment]
@rauls5382 I'm sorry, I did something stupid, and the profile file was empty. Anyway, it works :cloud: **wonderfully** :cloud:. This is exactly what I wanted. Thank you so much! Is there any obstacle to adding this to master?

**Comment by rauls5382** [comment]
There are some concerns with adding the new dependence to master. I'll work on it but it may take some time. Feel free to continue using my branch until then.

**Comment by whereswaldon** [comment]
Okay, thank you!

**Comment by levex** [comment]
Any news on this @rauls5382 ? I'd be happy to take on if you can't continue.

**Comment by ALTree** [comment]
@aalexand @nolanmar511 thoughts on this? Adding readline support should be relatively easy if some pure-go readline implementation is vendored; I guess the question here is whether it's fine to vendor a readline implementation or not.

**Comment by aalexand** [comment]
pprof is vendored into Golang source tree so I am not enthusiastic about adding a new dependency for this feature request. I wonder if it should be relatively easy to implement some limited readline-like-support without adding a new dependency.

**Comment by aalexand** [comment]
Could we use https://github.com/golang/crypto/blob/master/ssh/terminal/terminal.go? That seems to have limited history support. Is that less problematic to depend on in golang land?

**Comment by aalexand** [comment]
@rsc @hyangah @mvdan Do you see any issues (in terms of vendoring pprof into Go source tree) with pprof depending on https://github.com/golang/crypto/blob/master/ssh/terminal/terminal.go to implement limited history and editing support in the interactive mode?

**Comment by mvdan** [comment]
I don't know what the policy is around how much code can be vendored into the Go repository, sorry. I imagine Russ or other members of the Go team will have an opinion on it.

**Comment by andybons** [comment]
Regarding vendoring in the terminal stuff, go for it.

**Comment by rauls5382** [comment]
I'm sorry for the long silence on this. I think we can merge in my previous prototype while maintaining the existing version by default. I'll find some time to work on this.
