### ISSUE TITLE
Support option to disable early pruning args `(.*)` - some julia function names have parens in them

### ISSUE THREAD

**Issue by NHDaly** [google/pprof#573]
### What version of pprof are you using?

Recent master (acf8798be1f76c82483eaa0daf3fc93ab3d493b6)

### What operating system and processor architecture are you using?

MacOS, x86

### What did you do?

When profiling julia programs, some function names can contain `()`, such as overloading the "call" syntax for a struct object, which ends up printing like this:
```julia
(::MyStruct)(n::Int)
```

### What did you expect to see?

I would expect to see the above function name printed, but it gets pruned away.

### What did you see instead?

Instead, I see a frame named `<unknown>`, because the entire name was pruned away by this line:
https://github.com/google/pprof/blob/8ef5528bdba278d96081925d3d835926abc9d367/profile/prune.go#L40-L42

-----------------

It would be super great if we could make argument pruning optional for **two** reasons:
1. As described above, some Julia functions can have `(` in their names, and
2. Julia makes heavy use of "multiple dispatch," which means that a function can often have many, many overloads (called methods, in julia), for many different type combinations, and you need the argument types to identify which function this refers to.
   - For example, the `+` function has 184 overloads in the stdlib alone, before loading any packages. 
   - Packages will then register their _own_ overloads for their own types, which can do totally different things, meaning often the _arguments_ are the most important thing to distinguish which function is being called!
   - Users of PProf.jl have asked to print the full method signature in order to distinguish this exact case:
       - https://github.com/JuliaPerf/PProf.jl/issues/24

From what I can tell, it looks like this pruning is ultimately always called through `p.RemoveUninteresting()` and `applyFocus()`.
Does it seem plausible that we could perhaps add an option to configure `pprof` to skip this pruning step?

Thanks!

**Comment by aalexand** [comment]
I would prefer to avoid new knobs / options if they are not for broad use.
Can we instead modify the simplification code to respect this specific case?

**Comment by NHDaly** [comment]
Yeah, that makes sense.  I'm supportive of trying to find a way to do that, too. :)

**Comment by NHDaly** [comment]
Okay, actually, good news, it appears that I have figured out a way to get this to work.

I accidentally stumbled across the fact that apparently if you set `name` and `system_name` to *different* values, it will use the `name` verbatim without any modifications or pruning. So this seems to be like a very workable solution for us!

I've made use of this behavior in this PR: https://github.com/JuliaPerf/PProf.jl/pull/31 If you're able to, please let me know if I'm accidentally relying on undefined behavior, or if this indeed working as intended. Thank you very much! :)

Does the above sound right to you? Is this a reliable solution? 
Perhaps this behavior could be better documented?

Thanks!
~Nathan

**Comment by nolanmar511** [comment]
Awesome that a work-around was found!

Marking this as closed.
