### ISSUE TITLE
Are merges associative?

### ISSUE THREAD

**Issue by brancz** [google/pprof#589]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

If you are using pprof via `go tool pprof`, what's your `go env` output?

```
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/brancz/bin"
GOCACHE="/home/brancz/.cache/go-build"
GOENV="/home/brancz/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/brancz/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/brancz"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/brancz/src/github.com/polarsignals/polarsignals/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build659410674=/tmp/go-build -gno-record-gcc-switches"
```

If you run pprof from GitHub, what's the Git revision?

n/a

### What operating system and processor architecture are you using?

Linux amd64

### What did you do?

I have more profiles than I can load into memory and I would like to merge these profiles. I can write some code to batch them in chunks and merges them, but it is not entirely clear to me whether merging is associative.

From reading [the code](https://github.com/google/pprof/blob/1bf35d6f28c2d0288b382023b376d4db634119e2/profile/merge.go#L177-L189) I get the impression that it is associative, as essentially all it does is sum the sample values that have the same "identity" across the profiles. Am I understanding this correctly?

### What did you expect to see?

A little bit of documentation on how merging works, at least in the code, if not in the end user documentation.

### What did you see instead?

No documentation on the merging strategy.

---

If I understand it correctly then I'm more than happy to contribute some documentation describing this.

**Comment by brancz** [comment]
I wrote a quick non-exhaustive test with a small set of samples, and it appears that indeed merges are associative. https://gist.github.com/brancz/02608bf0ddf63dc540bd4747cff7a3cb

Would you like me to add a quick sentence to the docs about this detail?

**Comment by aalexand** [comment]
Adding a note to the Merge API is fine. For the pprof command line docs - I am not sure this level of detail is needed.

Also:

There is at least some specialization of the first profile [here](https://github.com/google/pprof/blob/4ba3a2d9526451ec89394c9f79e3ade3ded4e5e9/profile/merge.go#L437-L451). There may be other subtleties - now or in the future.

**Comment by brancz** [comment]
Thanks for the pointer! In my case I really only care about the streaming case, samples are ordered so it doesn't appear that I'm affected by this caveat. Adding it to the comment sounds good to me!

**Comment by brancz** [comment]
Opened #590, let me know if that is along the lines of what you were thinking! :)

**Comment by aalexand** [comment]
> Opened #590, let me know if that is along the lines of what you were thinking! :)

Yup, thanks! :)
