### ISSUE TITLE
Windows Disasm support

### ISSUE THREAD

**Issue by egonelbre** [google/pprof#592]
I've been annoyed of not having Windows disasm support for Go profiling a while now and was thinking of adding it. The thing that seems to be missing is PE support in `(*BinUtils).Open`, I'm sure I'll find more once I dig deeper. Is there something I should watch out for?

**Comment by kalyanac** [comment]
You'll need to look for tools to disassemble and symbolize the binary, and add the capability to parse the output. You will also need to add a sample binary for unit testing.

If the output is not compatible with the tools currently supported or changes significantly by version, long term support will be a problem because we may not be able to maintain it. 

@aalexand can decide if such a PR will be accepted.

**Comment by egonelbre** [comment]
With regards to disassemble and symbolize, I was thinking of using `gcc` since it can be relatively easily installed with https://jmeubank.github.io/tdm-gcc/ and others. Although, clang is similarly easy to install.

**Comment by aalexand** [comment]
pprof supports using `llvm-objdump`, `lvm-nm` and `llvm-symbolizer`. If there is a small change (say, ~50 LOC including tests) that makes that existing support work with Windows binaries, we can review and accept it.

If this is a larger change, I don't think we have the bandwidth to review and maintain it - Windows support is low priority on our list. Apologies for this.

But I hope it's the former and we can be of help.

**Comment by egonelbre** [comment]
At the moment it's looking like ~30LOC for adding PE support and then ~75LOC for a test (based on `TestOpenELF`).

I tried `llvm-nm`, but that didn't seem to get the line numbers properly. Using  gnu `addr2line` worked better.

Also needed rewrite `build_binaries.sh` to `build_binaries.go` due to incompatibilities with `sh` versions. But this change is optional and can be replaced with a separate bat file.

For rough estimate on the changes, the WIP is here https://github.com/google/pprof/compare/master...egonelbre:windows?expand=1.

**Comment by aalexand** [comment]
In spirit this looks reasonable if it's 100 lines and not 50 lines it's OK as long as the documentation is good and tests are good.

Some notes:

* Making sure that the path of using llvm-* tools works has been our preference recently. So if Binutils addr2line works it's good, but we should check llvm-symbolizer path and make it work too.
* For the *.sh file that creates the test binaries, it would be nice if we'd still have just these files, not *.bat files, but I don't know how tricky it is these days to have a sh interpreter on Windows. In any case, we should make sure that there is only one copy of the source code of these little test apps - your current patch appears to add new files while not changing the *.sh file which also has that source code. Documentation on re-generating the test binaries will need to be updated.
* The CI testing should be extended to test the Windows support. The coverage data should confirm that we cover the added paths.

**Comment by egonelbre** [comment]
> ... but I don't know how tricky it is these days to have a sh interpreter on Windows.

It's not tricky to have a `sh` interpreter, but there can be compatibility issues with the syntax. As an example, the current script didn't work with `sh` installed on my Windows machine. So it's more likely to break on different computers. It's easier to write a `.go` file and it's going to be more reliable with regards to compatibility. I dislike `.bat` files as well.

> ... your current patch appears to add new files while not changing the *.sh file which also has that source code ...

Not sure what you mean, the https://github.com/google/pprof/commit/f21e959a58f769b1ab0f453a4c80110c74077a6f change removed the `.sh` file and replaced with a `.go` file.

**Comment by aalexand** [comment]
> Not sure what you mean, the [f21e959](https://github.com/google/pprof/commit/f21e959a58f769b1ab0f453a4c80110c74077a6f) change removed the `.sh` file and replaced with a `.go` file.

I misread.
