### ISSUE TITLE
feature request:Consider add ignore option from files

### ISSUE THREAD

**Issue by theidexisted** [google/pprof#594]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

latest

### What operating system and processor architecture are you using?

RHEL 7 and AMD64

### What did you do?

I am using pprof to generate memory leak results, I wrote a library (similar to tcmalloc) to check memory and generate a dump file.
Then use pprof to visualize the dump file. I get many leak from libc and libdl, I want to ignore these functions. now we can only use regrex with `-ignore` options, I suggest adding an options `-ignore-file` to read the suppression function list from a file, something like the suppression list from [Google Address sanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer)

**Comment by aalexand** [comment]
This seems a rather niche feature request, so not sure we want to get this extra complexity into pprof. I'd want to at least see more use cases for it / people asking for it. If we decide to do this in the future, I think we should look into doing this via making the [settings](https://github.com/google/pprof/blob/master/internal/driver/settings.go) mechanism available in the CLI, not just in the web UI like now. Maybe a `-settings_file` flag or ability to select a pre-created settings by name via a flag like `-settings`, or something along those lines.
