### ISSUE TITLE
pprof support for golang 1.10.1 ?

### ISSUE THREAD

**Issue by Anon5710** [google/pprof#602]
This is probably not an issue, the chance is higher that I am doing something wrong. (Still new to golang)
If this is not the place, feel free to remove this post. (But please point me to a place where I can ask such questions :-) )

_**What version of pprof are you using?**_
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/USER/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/USER/go"
GOPROXY=""
GORACE=""
GOROOT="/home/USER/opt/go"
GOTMPDIR=""
GOTOOLDIR="/home/USER/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build584220800=/tmp/go-build -gno-record-gcc-switches"

_**What operating system and processor architecture are you using?**_
Linux Ubuntu 18.04 x64

**_What did you do?_**
Trying to use the net/http/pprof package with programs compiled with go 1.10.1.

I've installed the pprof handlers in my own HTTP server.

```
	router.Handle("/debug/pprof", http.HandlerFunc(pprof.Index))
	router.Handle("/debug/pprof/cmdline", http.HandlerFunc(pprof.Cmdline))
	router.Handle("/debug/pprof/profile", http.HandlerFunc(pprof.Profile))
	router.Handle("/debug/pprof/symbol", http.HandlerFunc(pprof.Symbol))
```

I can access the /debug/pprof index page, but all links on that index page return a **_404 Page not found error_**
![image](https://user-images.githubusercontent.com/77434690/106113211-7ef10480-614e-11eb-9682-71b14f7e5123.png)

http://localhost:8801/debug/block?debug=1
http://localhost:8801/debug/goroutine?debug=1
http://localhost:8801/debug/heap?debug=1
http://localhost:8801/debug/mutex?debug=1
http://localhost:8801/debug/threadcreate?debug=1
http://localhost:8801/debug/goroutine?debug=2

To my surprise, I was able to compile my program with go1.15.7, the page looked a bit different but the problem persists. I cannot access any of those links.
![image](https://user-images.githubusercontent.com/77434690/106113861-35ed8000-614f-11eb-9c44-f9d78310c862.png)

**_What did u expect_**
I expected to download profiles  (to be used with go tool pprof) when following the links on the /debug/pprof index page.

Regards,

**Comment by aalexand** [comment]
1. This is a Golang question, not a pprof question.
2. Golang version 1.10.1 is not a supported version, see https://golang.org/doc/devel/release.html#policy.

I'm closing this issue, further questions should be asked using Golang support means.
