### ISSUE TITLE
llvm-symbolizer 13.0.0 may have YAML output

### ISSUE THREAD

**Issue by MaskRay** [google/pprof#606]
https://reviews.llvm.org/D96289 proposes to add YAML output to llvm-symbolizer. I still need to convince myself that the output is useful. Since pprof parses llvm-symbolizer output (`internal/binutils/addr2liner_llvm.go`) I think you may have an opinion on it:)

**Comment by aalexand** [comment]
I don't think there is an out of the box YAML parser in Golang, so this is not interesting as this would require an additional dependency or custom parsing both of which are not exciting.

Do you know why YAML was chosen? JSON is a more common choice for machine-readable output. YAML is used more as a configuration language - i.e. human-read and -written.

**Comment by aalexand** [comment]
Also, frankly, even if it would be JSON, I don't see us switching to it. There isn't a lot of parsing code as the format is pretty simple and switching to JSON would still require supporting the old parsing code as well so why bother.
