### ISSUE TITLE
exe_windows_64.exe getting flagged by Antivirus

### ISSUE THREAD

**Issue by PandiPanda69** [google/pprof#607]
Hello guys,

On the current master branch (commit 1612e9be7af6e72931870e4b5710099f903476ef), the binary `internal/binutils/testdata/exe_windows_64.exe` is getting flagged by different Antivirus vendors as you can see on VT :
https://www.virustotal.com/gui/file/291aec4e3351ae7dc2b8426fd9e1e72f0f7b63b85a8d5588bd6d3f478a3c5f4c/detection

Obviously this is a false positive but it does trigger the Antivirus each time a git pull is performed.

**Comment by aalexand** [comment]
@egonelbre Do you mind taking a look? I don't want to roll back #593 but I also don't like having in the repo something that triggers AV checks.

**Comment by egonelbre** [comment]
Yeah, totally understand. It seems that building with clang the binary doesn't trigger the check.

One option might also be to rename to `exe_windows_64_exe`, although that might still trigger it.

**Comment by aalexand** [comment]
Any downsides of building with clang?

I suspect renaming wouldn't help as it probably inspects the content.

**Comment by egonelbre** [comment]
After building with `clang` I'm unable to get the symbols (i.e. `nm` and `llvm-nm` both report "no symbols"). I'm not sure what I'm missing, most likely some flag.

**Comment by egonelbre** [comment]
After tons of failed attempts, I got it finally to not trigger virustotal using MSYS2 gcc 10.2.0.
