### ISSUE TITLE
How to get the summary value from the cpu resources occupied by the nodes in the graph

### ISSUE THREAD

**Issue by njuptlzf** [google/pprof#618]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

If you are using pprof via `go tool pprof`, what's your `go env` output?
GOVERSION="go1.16.2"
If you run pprof from GitHub, what's the Git revision?

### What operating system and processor architecture are you using?
linux/amd64

### What did you do?

![pprof19](https://user-images.githubusercontent.com/53110312/112981222-74261080-918d-11eb-8274-15b01cc21f5f.png)

If possible, provide a recipe for reproducing the error.
Attaching a profile you are trying to analyze is good.

### What did you expect to see?
Please tell me how to get **cpu 109.07s**  by adding the value of the nodes in the graph

Can you provide a sample?

**Comment by njuptlzf** [comment]
I think I have fallen into a small misunderstanding. Based on the premise that multiple coroutines work together, it seems wrong to reverse the sampling time.

**Comment by nolanmar511** [comment]
To get to 109.07s, one would sum the flat (also called "self") values for all nodes displayed in the graph:

In the graph below, 1758.04ms + 0.24ms + 0ms = 1758.28ms (generated with `-nodecount=3`)
![image](https://user-images.githubusercontent.com/14046562/113315587-4db5c180-92c2-11eb-95a3-59fb71ea18e0.png)

The same holds true with the graph for this heap profile. 
0 + 2606.30kB + 765.39kB + 0kB = 3371.69kB.
![image](https://user-images.githubusercontent.com/14046562/113318307-32988100-92c5-11eb-93fc-4423e62f8f56.png)

This computation is done [here](https://github.com/google/pprof/blob/8eee2492667d02addff417580aea05e9d535866b/internal/report/report.go#L1180-L1183) (the label with this is written [here](https://github.com/google/pprof/blob/8eee2492667d02addff417580aea05e9d535866b/internal/report/report.go#L1190)).

**Comment by nolanmar511** [comment]
Feel free to re-open with any follow-ups. 
I'm marking this as closed for now.

**Comment by njuptlzf** [comment]
> Feel free to re-open with any follow-ups.
> I'm marking this as closed for now.

Clear, thx :+1:
