### ISSUE TITLE
Perform literal searches for invalid regex?

### ISSUE THREAD

**Issue by prattmic** [google/pprof#630]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

If you are using pprof via `go tool pprof`, what's your `go env` output?
If you run pprof from GitHub, what's the Git revision?

923b5ab0fc1a67b7d1902a06c66233c47e099120 (latest HEAD)

### What operating system and processor architecture are you using?

Linux, amd64

### What did you do?

If possible, provide a recipe for reproducing the error.
Attaching a profile you are trying to analyze is good.

Build and run this program:

```go
package main

import (
        "os"
        "runtime/pprof"
        "sync"
        "time"
)

type foo struct{}

//go:noinline
func (foo) value() {
        start := time.Now()
        for time.Since(start) < 1*time.Second {
        }
}

//go:noinline
func (*foo) pointer() {
        start := time.Now()
        for time.Since(start) < 1*time.Second {
        }
}

func main() {
        p, err := os.Create("/tmp/cpu.pprof")
        if err != nil {
                panic(err)
        }
        defer p.Close()
        if err := pprof.StartCPUProfile(p); err != nil {
                panic(err)
        }
        defer pprof.StopCPUProfile()

        var f foo
        var wg sync.WaitGroup
        wg.Add(2)
        go func () {
                defer wg.Done()
                f.value()
        }()
        go func () {
                defer wg.Done()
                f.pointer()
        }()

        wg.Wait()
}
```

Then naively attempt to disassemble the `pointer` method after noticing it in `top`, like so:

```
$ pprof /tmp/cpu.pprof
File: pprof_regexp
Type: cpu
Time: May 11, 2021 at 4:14pm (EDT)
Duration: 1.10s, Total samples = 1.99s (180.42%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 1990ms, 100% of 1990ms total
      flat  flat%   sum%        cum   cum%
    1490ms 74.87% 74.87%     1600ms 80.40%  runtime.nanotime
     210ms 10.55% 85.43%     1950ms 97.99%  time.Since
     140ms  7.04% 92.46%      140ms  7.04%  time.Time.Sub
     110ms  5.53% 97.99%      110ms  5.53%  runtime.nanotime1
      40ms  2.01%   100%     1060ms 53.27%  main.foo.value
         0     0%   100%      930ms 46.73%  main.(*foo).pointer
         0     0%   100%     1060ms 53.27%  main.main.func1
         0     0%   100%      930ms 46.73%  main.main.func2
(pprof) disasm main.(*foo).pointer
```

### What did you expect to see?

Disassembly output.

### What did you see instead?

```
parsing argument regexp main.(*foo).pointer: error parsing regexp: missing argument to repetition operator: `*`
```

This fails because `(*foo)` is an invalid regexp (no character for `*` to modify). This can be worked around by escaping the parentheses and asterisk, but this behavior is annoying and surprising to users that don't realize that is is a regexp, and just generally for working with Go programs, where such symbol names are common.

It would be nice to treat the argument as a literal if it is not a valid regexp, or even more generally to always search for the literal in addition to the regexp.

**Comment by nolanmar511** [comment]
At this point in time, we do document that filters require using regular expressions. 

Per team discussion, we have some concerns that using regular expressions but then falling back to string matching would also be potentially confusing. So we're closing this issue.
