### ISSUE TITLE
Add support for llvm-gsymutil

### ISSUE THREAD

**Issue by sfc-gh-sgiesecke** [google/pprof#632]
Symbolication is supported through addr2line, llvm-symbolizer and nm right now. When GSYM data is available for a binary, using llvm-gsymutil would be much faster and less memory-intensive than addr2line or llvm-symbolizer.

To make this fit in well with the execution model of pprof, it requires an extension of llvm-gsymutil to allow it to be fed the input addresses from stdin, as suggested by https://reviews.llvm.org/D102224

**Comment by nolanmar511** [comment]
Per discussion in https://github.com/google/pprof/pull/636, this is something we don't think makes sense to support directly within pprof at this time. 

Marking as closed.
