### ISSUE TITLE
Add support to block profiling in a period time

### ISSUE THREAD

**Issue by yunhjiang** [google/pprof#633]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

If you are using pprof via `go tool pprof`, what's your `go env` output?
If you run pprof from GitHub, what's the Git revision?

the output of `go env` as I'm using pprof through `go tool pprof`:
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yunhjiang/Library/Caches/go-build"
GOENV="/Users/yunhjiang/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yunhjiang/source/e2e/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/15/7w3r5fwd6tb6ty4l803wthjm0000gp/T/go-build004668976=/tmp/go-build -gno-record-gcc-switches -fno-common"

`go version` output:
go version
go version go1.14.2 darwin/amd64

### What operating system and processor architecture are you using?
Mac, amd64

### What did you do?

block profiling through https://127.0.0.3:443/debug/pprof/block

### What did you expect to see?
I hope that we can support the block profiling in a period time, similar to the CPU profiling.

### What did you see instead?
Currently the profiling will return the count/duration from the beginning, while some times we care for the block situation happens just during the profiling time.

**Comment by nolanmar511** [comment]
It looks like this question is related to the golang package "net/http/pprof/" (https://golang.org/pkg/net/http/pprof/). This repository  is for the pprof CLI (which can collect and visualize profiles from the endpoints related to "net/http/pprof/", but is distinct). Feature requests or issues related "net/http/pprof/" should be directed to golang's issue tracker at https://github.com/golang/go/issues.

The pprof CLI does support visualizing the difference between two profiles using the `-base` flag. This flag is documented at https://github.com/google/pprof/tree/master/doc#comparing-profiles.
