### ISSUE TITLE
Configurable default view?

### ISSUE THREAD

**Issue by wlandau** [google/pprof#640]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

```
$ pprof --version
pprof (part of gperftools 2.0)

Copyright 1998-2007 Google Inc.

This is BSD licensed software; see the source for copying conditions
and license information.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
```

### What operating system and processor architecture are you using?

Mac OS 10.15.7 with an Intel Core i7 (x86-064).

### Issue

`pprof -http` works correctly, but the default graph view is extremely difficult to interpret (even after reading the docs). I always switch to a different view, and these frequent manual switches add up to a lot of user friction. 

I would love to be able to set the default view (e.g. to the flame graph) using an environment variable.

**Comment by aalexand** [comment]
Perhaps you can manually navigate to `localhost:<port>/flamegraph` as opposed to `localhost:<port>`?

**Comment by aalexand** [comment]
I am not sure this should belong as an option to pprof given that a simple workaround exists.

**Comment by wlandau** [comment]
I like it, but is the URL stable? For my version of `pprof`, the browser accepts localhost:<port>/ui/flamegraph but not localhost:<port>/flamegraph.

**Comment by aalexand** [comment]
Ah, correct, there is the "/ui" prefix from #348. These paths should be stable enough for practical purposes.
