### ISSUE TITLE
CONTRIBUTING.md: Instructions to get the source code should be updated for new version of Go

### ISSUE THREAD

**Issue by mhansen** [google/pprof#648]
### What operating system and processor architecture are you using?
Google's defualt workstation golang binary:

```
$ uname -a
Linux markhansen.syd.corp.google.com 5.10.40-1rodete2-amd64 #1 SMP Debian 5.10.40-1rodete2 (2021-06-22) x86_64 GNU/Linux
$ which go
/usr/lib/google-golang/bin/go
$ go version
go version devel +b7a85e0003 linux/amd64
```

### What did you do?

Followed steps in `CONTRIBUTING.md` to get the source code. My `GOPATH` is empty and defaults to `~/go` (so I think you could maybe remove that bit of the CONTRIBUTING.md too?)

```
$ echo $GOPATH

$ go get github.com/google/pprof
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
# net
cgo: C compiler "clang" not found: exec: "clang": executable file not found in $PATH
# crypto/internal/boring
cgo: C compiler "clang" not found: exec: "clang": executable file not found in $PATH
```

I have some errors due to the new changes around go modules.

Then running the commands to run the tests:
```
$ cd $GOPATH/src/github.com/google/pprof
$ go test -v ./...
```

I tried going into `~/go/src/` but there is no `src` dir, only `~/go/bin/` and `~/go/pkg/`. The code seems to be in pkg/mod:

```
$ ls ~/go/pkg/mod/github.com/google
'pprof@v0.0.0-20210423192551-a2663126120b'/  'pprof@v0.0.0-20210827144239-02619b876842'/
```

### What did you expect to see?
No errors, and able to run the tests with instructions given.

### What did you see instead?
Errors and the tests weren't in the directory given.

**Comment by mhansen** [comment]
(this isn't particularly blocking me -- I'll just clone the repo -- but thought I'd file the bug in case this is affecting new contributors)

**Comment by mhansen** [comment]
Actually, let me check when I'm at my workstation tomorrow, the above is off-the-cuff and may be wrong.

**Comment by mhansen** [comment]
> for go version < 1.18, GOPATH needs to be set

Is 1.18 a typo? I thought GOPATH was only required before Go 1.8? https://rakyll.org/default-gopath/

**Comment by aalexand** [comment]
Hmm, I am not sure `go install github.com/google/pprof@latest` works that well for the development case, as I think it will download the sources into a versioned directory under ~/go/pkg/ ?

**Comment by mhansen** [comment]
Looking in the output of 'go help get' looks like maybe we want `go
get -d ***@***.***`, that says not to build or
install packages.

**Comment by chavey** [comment]
This older thread about 'go get' https://github.com/golang/go/issues/31529#issuecomment-484931428, suggests using git clone.

$ cd /tmp
$ git clone git@github.com:google/pprof.git
$ cd /tmp/pprof
$ go install // to get all dependencies as specified by go.mod

**Comment by chavey** [comment]
Should we had a section about using git clone OR are we ok with the current documentation?
