### ISSUE TITLE
Can't install on cluster

### ISSUE THREAD

**Issue by bantin** [google/pprof#656]
I can't install pprof using the suggested command. Trying to run `go get -u github.com/google/pprof` gives the following error:

go: downloading github.com/google/pprof v0.0.0-20211001005136-7fe48b4c820b
go get github.com/google/pprof: Lock /home/ba2617/go/pkg/mod/cache/download/github.com/google/pprof/@v/v0.0.0-20211001005136-7fe48b4c820b.lock: no locks available

I am trying to install on a Slurm cluster through my research institute (no sudo access) so Go is installed in my home directory, rather than the usual place. Here is the output of my `go env`

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ba2617/.cache/go-build"
GOENV="/home/ba2617/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ba2617/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ba2617/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/share/ctn/users/ba2617/binaries/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/share/ctn/users/ba2617/binaries/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2485901744=/tmp/go-build -gno-record-gcc-switches"
```

The operating system  is: CentOS Linux release 7.6.1810 (Core)

Any help would be appreciated. I have no idea what "no locks available" means.

**Comment by aalexand** [comment]
Using "go get" to install pprof is a rare but not unexpected way of using latest pprof (these instructions are listed in "Building pprof" on the main page). But the error doesn't really seem to be related to pprof. I would recommend asking elsewhere or searching for the error message on the web - I don't really have a way of reproducing or answering it.
