### ISSUE TITLE
FR: Input Folded Stacks Format

### ISSUE THREAD

**Issue by mhansen** [google/pprof#659]
@felixge's `pprofutils folded` allows converting [Folded Stacks format](https://queue.acm.org/detail.cfm?id=2927301#:~:text=The%20folded%20stack%2Dtrace%20format,trace%2C%20followed%20by%20a%20semicolon.) to pprof: https://github.com/felixge/pprofutils#folded

Folded Stacks are output by, and convertible from, a truly incredible number of profilers and profile data formats: see the `Folded Stacks` entry in Profilerpedia: https://docs.google.com/spreadsheets/d/1cVcHofphkQqk1yGeuBPVTit8HQ0oa5SlRM6gkHIagtw/edit#gid=0&range=I25. It seems it's such an easy format to output that many profilers use it directly, and the profilers that don't end up getting a converter so people can use Brendan Gregg's FlameGraph toolkit.

Bridging this gap between pprof and these profilers and these other data formats might allow pprof to be used to profile many more systems.

I'm thinking that if we have a folded stacks output format, then having a folded stacks input format would allow some powerful roundtripping use cases for ad-hoc analysis (things like using `sed` to rename stack frames).

I wonder if there's interest in supporting this in pprof core, or if you feel this should best live in other binaries, which output profile protos. But I could also argue that pprof has a great protobuf format, which allows external tools to handle this. Thoughts?

**Comment by aalexand** [comment]
@mhansen The folded stack format doesn't support indicating inlined frames or filenames, correct? In #649 you used `<root_fn>(filename);<fun2>(filename);<leaf_fn>(filename) <value>` format in a test but the `(filename)` part seems an "unofficial" extension?

**Comment by aalexand** [comment]
We don't have plans to support the folded format natively in pprof, closing. When needed, `pprofutils` should be used.
