### ISSUE TITLE
Why cum has negative values？

### ISSUE THREAD

**Issue by Treagzhao** [google/pprof#666]
![image](https://user-images.githubusercontent.com/8255607/140287225-4a6e52b0-cc98-4c67-b0cd-ebdf7d2962bf.png)

It saids negative cum values turns green.But i cannont understand,why cum value could be negative ?

**Comment by nolanmar511** [comment]
Negative values (cumulative or self values) are most likely to occur when one is doing profile comparison, which the pprof CLI does by subtracting one profile from another. More details on profile comparison can be found in pprof's docs at https://github.com/google/pprof/tree/master/doc#comparing-profiles. 

I'll send a PR to note this.
