### ISSUE TITLE
Help text is output to stderr instead of stdout

### ISSUE THREAD

**Issue by varungandhi-src** [google/pprof#678]
### What version of pprof are you using?

Go version 1.17.5

<details>
<summary>go env output</summary>

```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/varun/Library/Caches/go-build"
GOENV="/Users/varun/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/varun/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/varun/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tr/gylnxkts3bn0gyhhlrv8z9_m0000gn/T/go-build2429104617=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
</details>

### What operating system and processor architecture are you using?

arm64 macOS

### What did you do?

`go tool pprof --help`

### What did you expect to see?

The help text should be output to stdout so that it can be piped directly to a pager (such as `less`). Other parts of the go toolchain output help text to stdout (for example, `go help`, `go help get`). Ignoring the convenience aspect, it seems a little unusual to write help text to stdout, since it is not an error message or similar, it's literally the expected output.

### What did you see instead?

Help text is output to stderr.

**Comment by aalexand** [comment]
It's the [default behavior of the Golang flag package](https://cs.opensource.google/go/go/+/refs/tags/go1.17.5:src/flag/flag.go;l=369;drc=refs%2Ftags%2Fgo1.17.5), see also https://github.com/golang/go/issues/17284. While it can indeed can be argued if it's the right one, I don't think we'll deviate from it.
