### ISSUE TITLE
Glacially slow loading of profile data

### ISSUE THREAD

**Issue by lindsayad** [google/pprof#680]
### What version of pprof are you using?

`pprof` hash: d25a53d42d00
go env:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lindad/.cache/go-build"
GOENV="/home/lindad/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/lindad/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lindad/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/lindad/pprof/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3918463857=/tmp/go-build -gno-record-gcc-switches"
```

### What operating system and processor architecture are you using?

`uname -a`:
```
Linux pop-os 5.15.11-76051511-generic #202112220937~1640185481~21.10~b3a2c21 SMP Wed Dec 22 15:41:49 U x86_64 x86_64 x86_64 GNU/Linux
```

### What did you do?

Tried to load profiling data, e.g. `pprof foo.prof` where `foo.prof` was generated using `gperftools`. After 10 minutes, the profile hasn't loaded, e.g. I have yet to get the interactive `pprof` command prompt. The profiling data was generated by running an executable which links and uses several quite large dynamic libraries. If I generate a profile on a very small program, `pprof` loads the profile very quickly. My hypothesis for the glacial slowness is calls to `addr2line`. I see a half-dozen `addr2line` processes if I run `ps aux | grep addr2line` while `pprof foo.prof` is executing, and I've run across some incriminating articles regarding `addr2line` for example [here](https://eighty-twenty.org/2021/09/09/perf-addr2line-speed-improvement). Has anyone ever experienced this before? I have used `gperftools` and `pprof` very happily for a couple years and this is the first time I have encountered this issue. I should note that this is my first attempt at using `gperftools` and `pprof` on this particular machine. I wish I new what the important difference in environment and profiling versions was.

**Comment by lindsayad** [comment]
If there is a more appropriate place to raise my issue, please let me know.

**Comment by nolanmar511** [comment]
If it's possible to share the profile, that would be great (not sure that we'll have capacity to look at this soon, but having the ability to reproduce would be important). 

A few initial thoughts:
* If addr2line is the culprit, --symbolize=none (to skip symbolization) would make things quick (if this doesn't help, then addr2line can't be the culprit).
* it is known that the pprof CLI can be very slow with large profiles. Doing things to make the profile tree smaller, like changing the granularity (i.e. -granularity=files), focusing on a portion of the profile (`-focus`, `-ignore`, `-show`, `-hide`), and ignoring tags (`-taghide=.*`) can sometimes all help when that is the case.

**Comment by lindsayad** [comment]
Attached is the profile. If I pass `-symbolize=none` I get the command prompt instantaneously. 

[ordered-set0.prof.gz](https://github.com/google/pprof/files/7909066/ordered-set0.prof.gz)

**Comment by lindsayad** [comment]
I'm wondering whether there are any ideas for speeding this up and/or what changes were made in the tool-set such that profiling with symbolization proceeded at a good speed on my old system and is unusable on my current system. E.g. has `pprof` always used `addr2line`? Were there changes in `addr2line`? Based on my cursory reading, it seems like like the profile generator `gperftools` has probably always output addresses and `pprof` has always been the one symbolizing ... but I don't want to assume I know anything 😄 E.g. could there have been a change in `gperftools` that has led to the slow-down?

**Comment by lindsayad** [comment]
I'm curious if @rwcarlsen has any ideas about this

**Comment by lindsayad** [comment]
In case anyone ever stumbles on this issue, the problem is due to a specific commit in binutils, discussed on [this thread](https://sourceware.org/pipermail/binutils/2022-February/119701.html)
