### ISSUE TITLE
Graphviz output links to git.io

### ISSUE THREAD

**Issue by pilt** [google/pprof#697]
### What did you do?

I ran `go tool pprof` and its `web` command. In the generated graph, there is a message "See https://git.io/JfYMW for how to read the graph".

### What is the problem?

~~[The` git.io url redirection service stops working on April 29.](https://github.blog/changelog/2022-04-25-git-io-deprecation/)~~

source: https://github.com/google/pprof/blob/master/internal/report/report.go#L1218 

EDIT: I didn't catch the update saying they will keep the service running. They still encourage people to use other services though.

**Comment by aalexand** [comment]
Since the service will continue running, we can use the link.
