### ISSUE TITLE
Using same phrases for show_from and hide

### ISSUE THREAD

**Issue by viraptor** [google/pprof#700]
### What version of pprof are you using?

2021-09-30 / commit 7fe48b4c820be13151ae35ce5a5e3f54f1b53eef

### What operating system and processor architecture are you using?

macos / x64_86

### What did you do?

I'm running:
```
pprof -call_tree -svg -nodecount 1000 -show_from 'block in instrument' -hide 'block in instrument'
```

### What did you expect to see?

I expected the tree to get trimmed at the first `block in instrument` label, then all other `block in instrument` labels to be removed from the tree. (alternatively, I expected the trimming to happen independently of what's actually shown)

### What did you see instead?

The result is empty.
```
ShowFrom expression matched no samples
```
The hiding happened before `show_from` and affected what `show_from` can act on.

**Comment by aalexand** [comment]
You can try saving the filtered profile first - `pprof -proto -output=profile-copy.pb.gz --show_from 'block in instrument'`. Then do the hiding in a separate command.

**Comment by viraptor** [comment]
Cool, that does help :)
