### ISSUE TITLE
Filtering using -hide doesn't seem to work as expected

### ISSUE THREAD

**Issue by viraptor** [google/pprof#701]
### What version of pprof are you using?

2021-09-30 / commit 7fe48b4c820be13151ae35ce5a5e3f54f1b53eef

### What operating system and processor architecture are you using?

macos / x86_64

### What did you do?

I'm trying to hide some frames which are labeled with function "instrument" and come from a file `instrumentation.rb`
I graphed the file trying options: `-hide '.*instrumentation.rb.*'`, `-hide instrument` and some other combinations. In both cases some elements were removed and when filtering the file twice with `-proto -hide instrument` I get the message `Hide expression matched no samples`.

### What did you expect to see?

When I graph the call_tree I expected to not see any `instrument` blocks at all.

### What did you see instead?

There are many instrument blocks visible. Also:
```
$ lesspipe.sh market-filter.pb | grep instrumentation.rb | wc -l
      10
```

Did I misunderstand what `-hide` does?

**Comment by aalexand** [comment]
I don't fully understand the commands that were run. Can you list the full scenario with exact commands?

**Comment by viraptor** [comment]
Well... it turned out to be a typo on my side. Let me just close this issue in shame 🙇
