### ISSUE TITLE
[feature] Ignore functions or pkg specified by the user

### ISSUE THREAD

**Issue by Jun10ng** [google/pprof#712]
Hi team,

In my daily work, there is a “need" and it's solution, so I want to contribute it to the community.

In some applications, they use third party library to pre-process their requests, such as gls(goroutine local storage).
Then the library will makes our flame graph very **confusing**, with more "stack branch" and "more call layers".

for example,we have a profile as the following:
```
fnc_a; lib_scheduler_1; fnc_b 1
fnc_a; lib_scheduler_1; lib_scheduler_2; fnc_b 2
```
actually, in the example above, we alway have only 1 stack branch and 2 call layers.

```
fnc_a; fnc_b 3
```

I hope we can add a command like:

```
go tool pprof --ignore "lib_scheduler" [input profile] [out profile]
```
In the "out profile", we will delete/ignore all lib_scheduler function.

We could  have some discussion on it and I glad to raise a pull request to code it.
Thanks.

**Comment by aalexand** [comment]
I think you can achieve this using the `-hide` flag, e.g. `pprof -hide=lib_scheduler -proto -output=output.pb.gz input.pb.gz`.

**Comment by Jun10ng** [comment]
> I think you can achieve this using the `-hide` flag, e.g. `pprof -hide=lib_scheduler -proto -output=output.pb.gz input.pb.gz`.

Thanks! I closed this issue.
