### ISSUE TITLE
How can I located the function in pprof with method has "*" ?

### ISSUE THREAD

**Issue by huanggze** [google/pprof#733]
This is a duplicate question question to https://github.com/google/pprof/issues/512, since that's not solved while closed. Does any have a solution? thanks

It's about `list <regexp>` cannot take in an asterisk. And solutions from https://github.com/google/pprof/issues/512 not working.

```
(pprof) list (*conn).writeString
parsing argument regexp (*conn).writeString: error parsing regexp: missing argument to repetition operator: `*`
```

**Comment by nolanmar511** [comment]
Parenthesis would also need to be escaped (as would `.`s). For this, I'd try:

```
(pprof) list \(\*conn\)\.writeString
```

Documentation at https://github.com/google/pprof/tree/main/doc#annotated-code may be helpful here, too.
