### ISSUE TITLE
pprof -http no display source

### ISSUE THREAD

**Issue by wzlove** [google/pprof#738]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

If you are using pprof via `go tool pprof`, what's your `go env` output?
If you run pprof from GitHub, what's the Git revision?

### What operating system and processor architecture are you using?
darwin_amd64
### What did you do?
pprof -http=:8080

If possible, provide a recipe for reproducing the error.
Attaching a profile you are trying to analyze is good.

### What did you expect to see?
should display specificial code.

### What did you see instead?
![image](https://user-images.githubusercontent.com/35476126/202421969-018a9bcb-0cc2-4592-9565-48ed96c28331.png)

**Comment by Louis-Ye** [comment]
Can you elaborate more about what "should display specificial code" mean?

Also it would be nice if you can follow the instructions please:
"If possible, provide a recipe for reproducing the error. Attaching a profile you are trying to analyze is good."

**Comment by wzlove** [comment]
thinks, I has solved。[ways](https://juejin.cn/post/7197596428915228732)
