### ISSUE TITLE
Would pprof be open to using D2 (pure Go graph engine)?

### ISSUE THREAD

**Issue by alixander** [google/pprof#744]
https://github.com/terrastruct/d2

D2 is a new text-to-diagram tool. One of our users wanted to use it with pprof and I just wanted to check in to see if maintainers are open to a potential integration.

D2 is portable on any OS and is in pure Go.

Thanks.

**Comment by aalexand** [comment]
We are fairly satisfied with graphviz graph generation as the default graph generator. I don't think we want to take another dependency for a graph generation.

**Comment by aalexand** [comment]
Closing to reflect there is no plan to do this work, but everyone is welcome to share their thoughts.
