### ISSUE TITLE
pprof saves profiles in hidden alternate data streams on Windows due to : in filename

### ISSUE THREAD

**Issue by gbrayut** [google/pprof#75]
pprof includes the hostname:port as part of the filename for saved profiles, which causes the saved files to use [Alternate Data Streams (ADS)](https://blogs.technet.microsoft.com/askcore/2013/03/24/alternate-data-streams-in-ntfs/) when the file exists on an NTFS volume. Technically everything seems to still work, as referencing a saved file using the full name will retrieve the data from the alternate stream, but if those files are moved to another volume the ADS data could be lost.  They also appear to be 0 bytes, since most tools only show the size of the primary data stream. Example:

```PowerShell
go tool pprof -alloc_space http://hostname:6060/debug/pprof/heap
Fetching profile from http://hostname:6060/debug/pprof/heap
Saved profile in C:\Users\gbray\pprof\pprof.hostname:6060.alloc_objects.alloc_space.001.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) exit
#Run the above twice to save two profiles

C:\Users\gbray> dir .\pprof\


    Directory: C:\Users\gbray\pprof


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/21/2016   1:36 PM              0 pprof.hostname

C:\Users\gbray> Get-Item .\pprof\hostname -Stream * | ft FileName,Stream,Length

FileName                               Stream                                      Length
--------                               ------                                      ------
C:\Users\gbray\pprof\pprof.hostname    :$DATA                                      0
C:\Users\gbray\pprof\pprof.hostname    6060.alloc_objects.alloc_space.001.pb.gz    36909
C:\Users\gbray\pprof\pprof.hostname    6060.alloc_objects.alloc_space.002.pb.gz    37513
```

To prevent using ADS the pprof tool could either replace : with another character, or allow users to specify the filename for the saved profile.

Alternatively, to workaround the ADS issue users can run the following PowerShell script to extract the contents of the ADS and save them as normal files using _ instead of : 

```PowerShell
$streams = Get-Item ~\pprof\* -Stream * | ?{$_.Stream -ne ':$DATA'}
foreach($stream in $streams){
    $filename = $stream.FileName
    $streamname = $stream.Stream
    $newfilename = "${filename}_${streamname}"
    Write-Output "Starting $newfilename"
    Get-Content $filename -Stream $streamname -Encoding Byte | Set-Content $newfilename -Encoding Byte
    #Remove-Item $filename -Stream $streamname #Remove ADS
}
#Remove any 0 length files
#Get-Item ~\pprof\* | ?{$_.Length -eq 0} | Remove-Item -Force
```

**Comment by rauls5382** [comment]
The latest version of github.com/google/pprof doesn't include the address on the filename anymore.
You can use it as a replacement for go tool pprof.

The plan is to refresh the pprof in the Go distro by this version early on the Go 1.9 cycle.
