### ISSUE TITLE
FR: Public interface / function for reporting

### ISSUE THREAD

**Issue by coxley** [google/pprof#753]
# Summary

Hey folks!

We collect remote profiles quite often to send into the CLI. I've aggregated most of this workflow into our operational tooling, but the missing pieces are being able to generate an SVG/PNG/etc report from the raw data.

Now obviously I can shell out to `go tool pprof` — and will — but wondering if there's a reason the reporter is hidden behind `internal`? Would be better (for my situation) to pass around an `io.Reader` vs. piping the data between processes. 

Thanks for your time either way. :)

**Comment by coxley** [comment]
FWIW, this is my current hack around this in the meantime: https://gist.github.com/coxley/a0609812115ff425c06d58dc21fda289

**Comment by aalexand** [comment]
@coxley Not the answer you'd want but:

Maintaining API surfaces is [expensive](https://www.hyrumslaw.com/), we intentionally limit what we expose as public API and we don't plan to expand it in the near future.
