### ISSUE TITLE
Drops in numbers with -alloc_space option

### ISSUE THREAD

**Issue by sangelovic** [google/pprof#757]
### What version of pprof are you using?

I did `/usr/local/go/bin/go install github.com/google/pprof@latest`. My go env output is:

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/one/.cache/go-build"
GOENV="/home/one/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/one/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/one/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3433664934=/tmp/go-build -gno-record-gcc-switches"
```

### What operating system and processor architecture are you using?

Cross compiling for aarch64, pprof running on Debian 11 x86-64.

### What did you do?

I did four consecutive memory allocations dumps from my application using tcmalloc. Then I analyzed the dump files:

```
cd /home/one/go/bin
./pprof -top -sample_index=alloc_objects <path-to-app-with-debug-symbols> 0001.heap
./pprof -top -sample_index=alloc_objects <path-to-app-with-debug-symbols> 0002.heap
./pprof -top -sample_index=alloc_objects <path-to-app-with-debug-symbols> 0003.heap
./pprof -top -sample_index=alloc_objects <path-to-app-with-debug-symbols> 0004.heap
```

### What did you expect to see?

I expected to see ever-increasing (or at least the same) count of allocations inside. For example, in output from 0003.heap:

```
flat  flat%   sum%        cum   cum%
1107  2.58% 79.81%       5122 11.96%  CBnPropertyContents::CBnPropertyContents
```

But in output from 0004.heap I get:

```
flat  flat%   sum%        cum   cum%
688   1.20% 81.29%       4727  8.26%  CBnPropertyContents::CBnPropertyContents
```

The `flat` number is lower than in the previous dump. The same behavior is with `-alloc_space` option.

### What did you see instead?

The `flat` number in output from 0004.heap shall be the equal to or higher than 1107. Is this a bug? Or do I get the `-alloc_objects`/`-alloc_space` option wrong?

**Comment by aalexand** [comment]
> I did four consecutive memory allocations dumps from my application using tcmalloc.

Could you provide more details how you created those dumps?

**Comment by aalexand** [comment]
I suspect this is using https://github.com/gperftools/gperftools, not https://github.com/google/tcmalloc? I think the issue needs to go to those repos anyway as it's not pprof related.
