### ISSUE TITLE
Proto: document how function names should be structured

### ISSUE THREAD

**Issue by mttkay** [google/pprof#760]
At GitLab we are looking to integrate [Google Cloud Profiling](https://cloud.google.com/ruby/docs/reference/google-cloud-profiler/latest/Google-Cloud-Profiler) with our Ruby on Rails application. We use `stackprof` to produce profiles, then convert its results to pprof before uploading profiles to GCP.

During development we noticed that in the cloud profiling console, Ruby class and method names were [not properly aggregated](https://gitlab.com/gitlab-org/gitlab/-/issues/396453) and all shared the same color, as if it wasn't able to discern between them.

Through trial and error, we found that we could fix this by normalizing a canonical Ruby method and constant names such as `MyClass#method` or `MyModule::MyClass` to use dot-notation instead: `MyModule.MyClass.method`.

This wasn't clear by looking at the proto definition of what the cloud profiler expects one should send.

Would it make sense to specify exactly what `name` and `system_name` should look like? https://github.com/google/pprof/blob/main/proto/profile.proto#L213-L217

**Comment by aalexand** [comment]
I think this should be reported as a Cloud Profiler issue / question (e.g. using feedback in Cloud Console). The profile.proto format is largely agnostic on these visualization details.
