### ISSUE TITLE
Switch to the new flame graph implementation by default and remove d3 dependency

### ISSUE THREAD

**Issue by aalexand** [google/pprof#777]
d3 dependency has been heavy toil to carry in pprof - version upgrades like #748 can be difficult when there is a version mismatch between the OSS version and the internal version used at Google. We also don't feel that the d3 usage provides enough value.

The current plan is to switch to the new flame graph implementation in the web UI, then after some time turn down the current d3-based flame graph implementation and the d3 dependency overall.

**Comment by dhavaln-able** [comment]
Just checking, when the d3-dependency is supposed to be cleaned up?

**Comment by aalexand** [comment]
@ghemawat We can probably finish this cleanup now - PTAL #825.
