### ISSUE TITLE
-tagroot and -tagleaf in UI aren't including the tag name?

### ISSUE THREAD

**Issue by NHDaly** [google/pprof#811]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?

If you run pprof from GitHub, what's the Git revision?
Commit: 905365eefe3e5dc92b363189b7e5dbceba5cac82

### What operating system and processor architecture are you using?
MacOS M2

### What did you do?

Running the following profile with `-tagroot threadid` is not showing the `threadid:` tag name in the UI:
```
pprof -tagroot threadid -http localhost:60004 profile.pb.gz
```
[profile.pb.gz](https://github.com/google/pprof/files/13059066/profile.pb.gz)

### What did you expect to see?

I expected to see frames with the names `threadid:1` and `threadid:2`, similar to what I see in the screenshots from https://github.com/google/pprof/pull/649, which added this feature. For example, [this one](https://github.com/google/pprof/pull/649#issuecomment-930576324):

![135353189-70b26230-b4e2-40a0-99df-403f8b5347bd](https://github.com/google/pprof/assets/1582097/25421858-7a89-4176-ab68-ff817a37b02e)

### What did you see instead?

Instead, I just see frames with the *values* of the tags, i.e. `1` and `2`:
<img width="1819" alt="Screenshot 2023-10-20 at 4 50 45 PM" src="https://github.com/google/pprof/assets/1582097/ea930a2f-0e48-4e67-a414-e9204b759077">

And same for `-tagleaf`:
<img width="1007" alt="Screenshot 2023-10-20 at 4 46 09 PM" src="https://github.com/google/pprof/assets/1582097/f4d98adb-6e46-4dac-99f6-b9e9bc4c43b4">

Was this changed on purpose at some point, or is this a bug? I think I very much preferred the view I expected.

**Comment by aalexand** [comment]
The tag name for these nodes is placed in the filename field when the profile with `-tagroot` or `-tagleaf` is generated. But I think the default granularity is `-functions` which discards the filename during the aggregation. Try passing `-filefunctions` flag.

**Comment by aalexand** [comment]
Closing for now, we can re-open if needed.

**Comment by NHDaly** [comment]
Thanks. Maybe we can figure it out with the right settings then, cool. 👍 

😅 That doesn't seem to be quite right either - this shows _only_ the tag name, but not the tag value:
<img width="1115" alt="Screenshot 2023-10-22 at 8 53 56 PM" src="https://github.com/google/pprof/assets/1582097/dbe5117c-9268-4946-941d-22eab19cc6d5">
<img width="1100" alt="Screenshot 2023-10-22 at 8 55 08 PM" src="https://github.com/google/pprof/assets/1582097/49ab39dd-b8b8-4c1d-823c-7707a7e66633">

**Comment by NHDaly** [comment]
^ @aalexand: I just reread this thread, and I think this was not resolved. Could I ask you to reopen until we can figure out the right set of flags?
