### ISSUE TITLE
New flame graph appears to reset the profile state in an unexpected way

### ISSUE THREAD

**Issue by aalexand** [google/pprof#812]
Steps to reproduce:

* Run a command like

  ```
  go run pprof.go -http $HOSTNAME:8080 internal/report/testdata/sample.bin internal/report/testdata/sample.cpu
  ```
  Any profile can be used.

* Visit the printed URL to get to the web UI. The graph view will display as expected.
* Then navigate to View -> Flame Graph (which is the new d3-less implementation of the flame graph view).
   The flame graph will display as expected.
* Now navigate back to the graph view. It will not display this time and "Focus expression matched no samples" message shows.
* Old flame graph view also doesn't work at this point. The new one still displays correctly.

@ghemawat FYI

**Comment by ghemawat** [comment]
I will send a PR with a fix. Thanks for the report.
