### ISSUE TITLE
Compatibility guarantees for Profile-Guided Optimization (PGO) purposes with Go 

### ISSUE THREAD

**Issue by zamazan4ik** [google/pprof#821]
Hi!

We are evaluating using [Profile-Guided Optimization (PGO)](https://go.dev/doc/pgo) with Go. Right now the Go compiler stores the profile as a file, that later can be reused. However, I cannot find the information about the backward/forward compatibility guarantees of the pprof format (the format used by the Go compiler). For us, it's important to know because right now we cannot understand whether will it be possible to use PGO profiles from the older compiler with a newer Go version or not (and vice versa).

In LLVM PGO infrastructure we already [met](https://github.com/llvm/llvm-project/issues/52683) some problems with that - the Clang/LLVM documentation also [hasn't](https://discourse.llvm.org/t/profile-guided-optimization-pgo-related-questions-and-suggestions/75232/2) this information yet. We want to avoid such problems with Go in the future.

### What version of pprof are you using?

N/A

### What operating system and processor architecture are you using?

Any

### What did you do?

No error - just a question

### What did you expect to see?

I expect to see the compatibility guarantees information somewhere in the pprof format documentation.

### What did you see instead?

I cannot find the information about the backward compatibility guarantees.

**Comment by aalexand** [comment]
I think this question should be directed to the Golang team / project. While there are implications of compatibility at the format level too, they are more important at the level of how the runtime itself deals with the format.

**Comment by aalexand** [comment]
Feel free to CC me when you file this question in Golang project. I can speak for pprof as needed.
