### ISSUE TITLE
Patch CVE for d3-color

### ISSUE THREAD

**Issue by ziler-orca** [google/pprof#830]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?
latest

If you are using pprof via `go tool pprof`, what's your `go env` output?

If you run pprof from GitHub, what's the Git revision?

### What operating system and processor architecture are you using?
Linux 5.10.205-195.807.amzn2.x86_64

### What did you do?
Ran a vulnerability scanning tool

### What did you expect to see?

Patch the following CVE please

CVE | Package Name | Vulnerable Version | Patched Version | Package Path
-- | -- | -- | -- | --
GHSA-36jr-mh4h-2g58 | d3-color-1.4.1 | 1.4.1 | 3.1.0 | /usr/local/go/src/cmd/vendor/github.com/google/pprof/third_party/d3flamegraph/package-lock.json

### What did you see instead?
Vulnerability showed up by our scan tool

**Comment by aalexand** [comment]
#825 removed d3 flamegraph dependency.
