### ISSUE TITLE
New flamegraph:  'hover shows details on the top' from old flame-graph missing

### ISSUE THREAD

**Issue by hzeller** [google/pprof#836]
### What version of pprof are you using?

github head.

### What operating system and processor architecture are you using?
Relveant  in this contetxt Chromium 122.0.6261.69

### What did you do?

Explore the flamegraph in the http UI.

The new flamegraph is nice, but it is missing one feature that was neat in the 'old' version: showing detailed information about a particular node (such long form of demangled name Edit: CPU % is already on the top right).

Currently, this information _is_ there, but only as a hover tooltip, i.e. it takes a second or so to show up.

I like to navigate quickly and hover over interesting nodes and want to see the details immediately, e.g. in the left top corner where it used to be in the 'old' flamegraph. The space on the top is is unused (currently, I don't know if you plan anything there), but it would be nice to have the 'old' feature back (or maybe I already can configure it somewhere and I don't know about it ?)

![hover-flamegraph2](https://github.com/google/pprof/assets/140937/bfaaf949-9ecd-487d-b584-34d4d2baa4a0)

**Comment by aalexand** [comment]
@ghemawat FYI, it's an older issue, but not sure if you saw it.

**Comment by ghemawat** [comment]
I'll take a look
