### ISSUE TITLE
Nice to have: 'grab' cursor when dragging the graph

### ISSUE THREAD

**Issue by hzeller** [google/pprof#837]
### What version of pprof are you using?

Github head.

### What UI question did you have in mind ?

Not a bug. This is merely UI idea that came to mind playing with the web-UI, specifically the 'graph' view.

When dragging the graph view, the mouse-cursor stays the same as regular pointer.
However, from a user feedback perspective -- seeing that this is holding the graph and moving it around -- it would be neat if the cursor was changing into the 'grab cursor' symbol (the little hand that 'holds on' to the thing being dragged). 

I think the [CSS cursor property](https://www.w3schools.com/cssref/pr_class_cursor.php) would be `cursor: grabbing`.

**Comment by talohana** [comment]
Should be added in #854

**Comment by hzeller** [comment]
Thank you!
