### ISSUE TITLE
don't need profile after convert

### ISSUE THREAD

**Issue by zhangguanzhang** [google/pprof#846]
### What did you do?

```
$ pprof -svg -seconds 30 http://127.0.0.1:20129/debug/pprof/profile > test.svg
Fetching profile over HTTP from http://127.0.0.1:20129/debug/pprof/profile?seconds=30
Please wait... (30s)
Saved profile in /root/pprof/pprof.main.samples.cpu.001.pb.gz
```

I don't want keep the `/root/pprof/pprof.main.samples.cpu.001.pb.gz` after to svg

**Comment by aalexand** [comment]
You will have to remove the file manually, I don't think we will change easily the current behavior. These files are usually too small to care though, I'd just leave them.
