### ISSUE TITLE
 [Help Needed] How to Accelerate `pprof -top` Command Execution for Profiling Data?

### ISSUE THREAD

**Issue by PengWei97** [google/pprof#853]
### What version of pprof are you using?

```bash
(moose) pw-moose@pwmoose-PowerEdge-T640:~/go/bin$ go version
go version go1.18.1 linux/amd64
```
> If you run pprof from GitHub, what's the Git revision?

Today, I used `go install github.com/google/pprof@latest` to install, so I think it is the latest version of pprof, but I cannot get the specific version number.

### What operating system and processor architecture are you using?
```bash
(moose) pw-moose@pwmoose-PowerEdge-T640:~$ uname -a
Linux pwmoose-PowerEdge-T640 6.5.0-28-generic #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
### What did you do?

I am currently working with profiling data generated by the `MOOSE` simulation framework, specifically using the `pprof` tool to analyze performance. I used the following command to generate profiling data with 32 processes:

```
MOOSE_PROFILE_BASE=run3_ mpiexec -n 32 ~/projocts/panda/panda-oprof -i s2_bicrystal_cp_elastic3.i > 01.log
```

This command generated 32 profiling data files named `run3_[0-31].prof`. I am trying to generate a performance report using the following command:

```
pprof -top ~/projocts/panda/panda-oprof run3_1.prof
```
[prof_and_oprof.zip](https://github.com/google/pprof/files/15107684/prof_and_oprof.zip)

### What did you see instead?
However, I am facing an issue where this command takes an unexpectedly long time to execute; it has been over 30 minutes without yielding any results.

### What did you expect to see?
I would appreciate any insights or suggestions on how to accelerate the execution of this command. Are there specific flags or methods within pprof that can be utilized to optimize the processing time for large profiling data files?

Thank you for your help and looking forward to your suggestions.

Best regards,

Wei

**Comment by aalexand** [comment]
Closing. We can reopen once there's a reproducer.
