### ISSUE TITLE
The calling relationship of CPU profile results is wrong

### ISSUE THREAD

**Issue by yuangcao** [google/pprof#869]
### What version of pprof are you using?

I use pprof via `go tool pprof`, the output of `go env` is:

```
GO111MODULE=''                                                                                                                        
GOARCH='amd64'                                                                                                                        
GOBIN=''                                                                                                                              
GOCACHE='/home/ops/.cache/go-build'                                                                                                   
GOENV='/home/ops/.config/go/env'                                                                                                      
GOEXE=''                                                                                                                              
GOEXPERIMENT=''                                                                                                                       
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/ops/go/pkg/mod' 
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/ops/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2660239872=/tmp/go-build -gno-record-gcc-switches'
```

### What operating system and processor architecture are you using?

os: CentOS Linux release 7.6.1810 (Core)
processor architecture: x86_64

### What did you do?

I use `pprof` to get the cpu usage info of my program and get the flamegraph of the cpu profile.

```
go tool pprof http://localhost:16220/debug/pprof/profile\?seconds\=1300 # output file ~/pprof/cpu.001.pb.gz
go tool pprof -http :11111 ~/pprof/cpu.001.pb.gz
wget -O flamegraph.htm http://localhost:11111/ui/flamegraph
```
### What did you expect to see?

Upper boxes call boxes below them.

### What did you see instead?

Many upper boxes are not callers of boxes below them. For example, an upper box is `proto.Actions.Contains` and a box directly below it is `wal.(*logEntryStorage).open`. But the function `proto.Actions.Contains` is:
```golang
func (actions Actions) Contains(action Action) bool {
	if len(actions) == 0 {
		return false
	}
	for _, a := range actions {
		if a == action {
			return true
		}
	}
	return false
}
```
It doesn't call the function `wal.(*logEntryStorage).open`.

I also got the svg file and it had the same infomation of the flamegraph.

Why is this happening and what should I do to get a good cpu profile? Thanks for your time!

**Comment by nolanmar511** [comment]
In this case, the I think the pprof CLI is acting primarily as a profile visualizer for the profile generated by the http page visited.

Code used for collection is part of the main golang repo (specifically https://github.com/golang/go/tree/master/src/runtime/pprof), so issues identified here seem somewhat outside the scope of this repo.  If you do post an issue in https://github.com/golang/go, it might be helpful to include a reproducer or share a profile if possible.

**Comment by aalexand** [comment]
In addition to what @nolanmar511 said, I would add that for successful investigation more data would be needed. In the report there is no full screenshot, no profile, no exact instructions on how to reproduce the issue end to end. Other than guessing, the chances that anyone would be able to help / answer the question are very slim.

**Comment by yuangcao** [comment]
Thank you. I will add some detailed information and post a issue in the main golang repo.
