### ISSUE TITLE
Unknown heap traces

### ISSUE THREAD

**Issue by anishjain94** [google/pprof#871]
Please answer these questions before submitting your issue. Thanks!

### What version of pprof are you using?
GOVERSION='go1.22.4'

### What operating system and processor architecture are you using?
Linux/UNIX on a t2.large instance. 

### What did you do?
I am trying to analyze a heap profile. But in the image that is being generated, i can only see unknown. No stack traces, nothing. Can you help me why is this happening?

<img width="1125" alt="Screenshot 2024-06-10 at 15 58 52" src="https://github.com/google/pprof/assets/25664697/b6845cad-8501-4fbc-a7dc-d21f1b8549cd">

### What did you expect to see?
Stack traces

### What did you see instead?
Unknown

**Comment by aalexand** [comment]
Please include full steps to reproduce the issue. The current instructions do not provide enough details. I also suspect this may be more of a question for the golang repo.
