### ISSUE TITLE
How to efficiently compress pprof files?

### ISSUE THREAD

**Issue by zdyj3170101136** [google/pprof#877]
We run a continuous performance analysis system in production (getting a pprof file every minute).

In fact, most of the content of a service's pprof file should be the same, except for the number of occurrences of different call 
stacks.

 Is there any way to efficiently compress multiple pprof files?

To support the following use cases:

1. Reduce storage overhead.

2. Efficiently aggregate a day's performance files. (Thousands).

**Comment by aalexand** [comment]
There isn't standard support in the pprof format for sharing data between profiles.
