### ISSUE TITLE
Add release tag

### ISSUE THREAD

**Issue by GuangmingLuo** [google/pprof#883]
Please answer these questions before submitting your issue. Thanks!

### What did you do?

[Kitex](https://github.com/cloudwego/kitex) has integrated pprof for [request profiler](https://www.cloudwego.io/docs/kitex/tutorials/advanced-feature/profiler/)

### What did you expect to see?
I am wondering if pprof can have some stable release tags or version?

**Comment by aalexand** [comment]
Sorry, no plans to do this, see #714.
